// ─────────────────────────────────────────────────────────────────────────────
// CRAFTING SYSTEM DATABASES
// ─────────────────────────────────────────────────────────────────────────────
// All elements from the periodic table, each with a curated color.
export const BASIC_ELEMENTS = [
  // Period 1
  { id: "H",   symbol: "H",   label: "H",    name: "Hydrogen",       atomicNum: 1,   color: "#0ea5e9", dark: "#0369a1" },
  { id: "He",  symbol: "He",  label: "He",   name: "Helium",         atomicNum: 2,   color: "#94a3b8", dark: "#475569" },
  // Period 2
  { id: "Li",  symbol: "Li",  label: "Li",   name: "Lithium",        atomicNum: 3,   color: "#ec4899", dark: "#be185d" },
  { id: "Be",  symbol: "Be",  label: "Be",   name: "Beryllium",      atomicNum: 4,   color: "#84cc16", dark: "#4d7c0f" },
  { id: "B",   symbol: "B",   label: "B",    name: "Boron",          atomicNum: 5,   color: "#f59e0b", dark: "#b45309" },
  { id: "C",   symbol: "C",   label: "C",    name: "Carbon",         atomicNum: 6,   color: "#4b5563", dark: "#1f2937" },
  { id: "N",   symbol: "N",   label: "N",    name: "Nitrogen",       atomicNum: 7,   color: "#6366f1", dark: "#4338ca" },
  { id: "O",   symbol: "O",   label: "O",    name: "Oxygen",         atomicNum: 8,   color: "#ef4444", dark: "#b91c1c" },
  { id: "F",   symbol: "F",   label: "F",    name: "Fluorine",       atomicNum: 9,   color: "#10b981", dark: "#059669" },
  { id: "Ne",  symbol: "Ne",  label: "Ne",   name: "Neon",           atomicNum: 10,  color: "#f97316", dark: "#c2410c" },
  // Period 3
  { id: "Na",  symbol: "Na",  label: "Na",   name: "Sodium",         atomicNum: 11,  color: "#f97316", dark: "#c2410c" },
  { id: "Mg",  symbol: "Mg",  label: "Mg",   name: "Magnesium",      atomicNum: 12,  color: "#84cc16", dark: "#4d7c0f" },
  { id: "Al",  symbol: "Al",  label: "Al",   name: "Aluminum",       atomicNum: 13,  color: "#94a3b8", dark: "#475569" },
  { id: "Si",  symbol: "Si",  label: "Si",   name: "Silicon",        atomicNum: 14,  color: "#64748b", dark: "#334155" },
  { id: "P",   symbol: "P",   label: "P",    name: "Phosphorus",     atomicNum: 15,  color: "#dc2626", dark: "#991b1b" },
  { id: "S",   symbol: "S",   label: "S",    name: "Sulfur",         atomicNum: 16,  color: "#f59e0b", dark: "#b45309" },
  { id: "Cl",  symbol: "Cl",  label: "Cl",   name: "Chlorine",       atomicNum: 17,  color: "#9333ea", dark: "#6b21a8" },
  { id: "Ar",  symbol: "Ar",  label: "Ar",   name: "Argon",          atomicNum: 18,  color: "#94a3b8", dark: "#475569" },
  // Period 4
  { id: "K",   symbol: "K",   label: "K",    name: "Potassium",      atomicNum: 19,  color: "#ec4899", dark: "#be185d" },
  { id: "Ca",  symbol: "Ca",  label: "Ca",   name: "Calcium",        atomicNum: 20,  color: "#eab308", dark: "#a16207" },
  { id: "Sc",  symbol: "Sc",  label: "Sc",   name: "Scandium",       atomicNum: 21,  color: "#64748b", dark: "#334155" },
  { id: "Ti",  symbol: "Ti",  label: "Ti",   name: "Titanium",       atomicNum: 22,  color: "#475569", dark: "#1e293b" },
  { id: "V",   symbol: "V",   label: "V",    name: "Vanadium",       atomicNum: 23,  color: "#7c3aed", dark: "#5b21b6" },
  { id: "Cr",  symbol: "Cr",  label: "Cr",   name: "Chromium",       atomicNum: 24,  color: "#0891b2", dark: "#0e7490" },
  { id: "Mn",  symbol: "Mn",  label: "Mn",   name: "Manganese",      atomicNum: 25,  color: "#a855f7", dark: "#7e22ce" },
  { id: "Fe",  symbol: "Fe",  label: "Fe",   name: "Iron",           atomicNum: 26,  color: "#78716c", dark: "#44403c" },
  { id: "Co",  symbol: "Co",  label: "Co",   name: "Cobalt",         atomicNum: 27,  color: "#0ea5e9", dark: "#0369a1" },
  { id: "Ni",  symbol: "Ni",  label: "Ni",   name: "Nickel",         atomicNum: 28,  color: "#65a30d", dark: "#3f6212" },
  { id: "Cu",  symbol: "Cu",  label: "Cu",   name: "Copper",         atomicNum: 29,  color: "#d97706", dark: "#92400e" },
  { id: "Zn",  symbol: "Zn",  label: "Zn",   name: "Zinc",           atomicNum: 30,  color: "#0891b2", dark: "#0e7490" },
  { id: "Ga",  symbol: "Ga",  label: "Ga",   name: "Gallium",        atomicNum: 31,  color: "#84cc16", dark: "#4d7c0f" },
  { id: "Ge",  symbol: "Ge",  label: "Ge",   name: "Germanium",      atomicNum: 32,  color: "#64748b", dark: "#334155" },
  { id: "As",  symbol: "As",  label: "As",   name: "Arsenic",        atomicNum: 33,  color: "#65a30d", dark: "#3f6212" },
  { id: "Se",  symbol: "Se",  label: "Se",   name: "Selenium",       atomicNum: 34,  color: "#f97316", dark: "#c2410c" },
  { id: "Br",  symbol: "Br",  label: "Br",   name: "Bromine",        atomicNum: 35,  color: "#f43f5e", dark: "#be123c" },
  { id: "Kr",  symbol: "Kr",  label: "Kr",   name: "Krypton",        atomicNum: 36,  color: "#94a3b8", dark: "#475569" },
  // Period 5
  { id: "Rb",  symbol: "Rb",  label: "Rb",   name: "Rubidium",       atomicNum: 37,  color: "#ec4899", dark: "#be185d" },
  { id: "Sr",  symbol: "Sr",  label: "Sr",   name: "Strontium",      atomicNum: 38,  color: "#eab308", dark: "#a16207" },
  { id: "Y",   symbol: "Y",   label: "Y",    name: "Yttrium",        atomicNum: 39,  color: "#64748b", dark: "#334155" },
  { id: "Zr",  symbol: "Zr",  label: "Zr",   name: "Zirconium",      atomicNum: 40,  color: "#475569", dark: "#1e293b" },
  { id: "Nb",  symbol: "Nb",  label: "Nb",   name: "Niobium",        atomicNum: 41,  color: "#7c3aed", dark: "#5b21b6" },
  { id: "Mo",  symbol: "Mo",  label: "Mo",   name: "Molybdenum",     atomicNum: 42,  color: "#64748b", dark: "#334155" },
  { id: "Tc",  symbol: "Tc",  label: "Tc",   name: "Technetium",     atomicNum: 43,  color: "#94a3b8", dark: "#475569" },
  { id: "Ru",  symbol: "Ru",  label: "Ru",   name: "Ruthenium",      atomicNum: 44,  color: "#94a3b8", dark: "#475569" },
  { id: "Rh",  symbol: "Rh",  label: "Rh",   name: "Rhodium",        atomicNum: 45,  color: "#94a3b8", dark: "#475569" },
  { id: "Pd",  symbol: "Pd",  label: "Pd",   name: "Palladium",      atomicNum: 46,  color: "#94a3b8", dark: "#475569" },
  { id: "Ag",  symbol: "Ag",  label: "Ag",   name: "Silver",         atomicNum: 47,  color: "#94a3b8", dark: "#475569" },
  { id: "Cd",  symbol: "Cd",  label: "Cd",   name: "Cadmium",        atomicNum: 48,  color: "#65a30d", dark: "#3f6212" },
  { id: "In",  symbol: "In",  label: "In",   name: "Indium",         atomicNum: 49,  color: "#84cc16", dark: "#4d7c0f" },
  { id: "Sn",  symbol: "Sn",  label: "Sn",   name: "Tin",            atomicNum: 50,  color: "#94a3b8", dark: "#475569" },
  { id: "Sb",  symbol: "Sb",  label: "Sb",   name: "Antimony",       atomicNum: 51,  color: "#64748b", dark: "#334155" },
  { id: "Te",  symbol: "Te",  label: "Te",   name: "Tellurium",      atomicNum: 52,  color: "#f97316", dark: "#c2410c" },
  { id: "I",   symbol: "I",   label: "I",    name: "Iodine",         atomicNum: 53,  color: "#7c3aed", dark: "#5b21b6" },
  { id: "Xe",  symbol: "Xe",  label: "Xe",   name: "Xenon",          atomicNum: 54,  color: "#94a3b8", dark: "#475569" },
  // Period 6
  { id: "Cs",  symbol: "Cs",  label: "Cs",   name: "Caesium",        atomicNum: 55,  color: "#ec4899", dark: "#be185d" },
  { id: "Ba",  symbol: "Ba",  label: "Ba",   name: "Barium",         atomicNum: 56,  color: "#eab308", dark: "#a16207" },
  { id: "La",  symbol: "La",  label: "La",   name: "Lanthanum",      atomicNum: 57,  color: "#10b981", dark: "#059669" },
  { id: "Ce",  symbol: "Ce",  label: "Ce",   name: "Cerium",         atomicNum: 58,  color: "#10b981", dark: "#059669" },
  { id: "Pr",  symbol: "Pr",  label: "Pr",   name: "Praseodymium",   atomicNum: 59,  color: "#10b981", dark: "#059669" },
  { id: "Nd",  symbol: "Nd",  label: "Nd",   name: "Neodymium",      atomicNum: 60,  color: "#10b981", dark: "#059669" },
  { id: "Pm",  symbol: "Pm",  label: "Pm",   name: "Promethium",     atomicNum: 61,  color: "#10b981", dark: "#059669" },
  { id: "Sm",  symbol: "Sm",  label: "Sm",   name: "Samarium",       atomicNum: 62,  color: "#10b981", dark: "#059669" },
  { id: "Eu",  symbol: "Eu",  label: "Eu",   name: "Europium",       atomicNum: 63,  color: "#10b981", dark: "#059669" },
  { id: "Gd",  symbol: "Gd",  label: "Gd",   name: "Gadolinium",     atomicNum: 64,  color: "#10b981", dark: "#059669" },
  { id: "Tb",  symbol: "Tb",  label: "Tb",   name: "Terbium",        atomicNum: 65,  color: "#10b981", dark: "#059669" },
  { id: "Dy",  symbol: "Dy",  label: "Dy",   name: "Dysprosium",     atomicNum: 66,  color: "#10b981", dark: "#059669" },
  { id: "Ho",  symbol: "Ho",  label: "Ho",   name: "Holmium",        atomicNum: 67,  color: "#10b981", dark: "#059669" },
  { id: "Er",  symbol: "Er",  label: "Er",   name: "Erbium",         atomicNum: 68,  color: "#10b981", dark: "#059669" },
  { id: "Tm",  symbol: "Tm",  label: "Tm",   name: "Thulium",        atomicNum: 69,  color: "#10b981", dark: "#059669" },
  { id: "Yb",  symbol: "Yb",  label: "Yb",   name: "Ytterbium",      atomicNum: 70,  color: "#10b981", dark: "#059669" },
  { id: "Lu",  symbol: "Lu",  label: "Lu",   name: "Lutetium",       atomicNum: 71,  color: "#10b981", dark: "#059669" },
  { id: "Hf",  symbol: "Hf",  label: "Hf",   name: "Hafnium",        atomicNum: 72,  color: "#475569", dark: "#1e293b" },
  { id: "Ta",  symbol: "Ta",  label: "Ta",   name: "Tantalum",       atomicNum: 73,  color: "#475569", dark: "#1e293b" },
  { id: "W",   symbol: "W",   label: "W",    name: "Tungsten",       atomicNum: 74,  color: "#475569", dark: "#1e293b" },
  { id: "Re",  symbol: "Re",  label: "Re",   name: "Rhenium",        atomicNum: 75,  color: "#475569", dark: "#1e293b" },
  { id: "Os",  symbol: "Os",  label: "Os",   name: "Osmium",         atomicNum: 76,  color: "#475569", dark: "#1e293b" },
  { id: "Ir",  symbol: "Ir",  label: "Ir",   name: "Iridium",        atomicNum: 77,  color: "#475569", dark: "#1e293b" },
  { id: "Pt",  symbol: "Pt",  label: "Pt",   name: "Platinum",       atomicNum: 78,  color: "#94a3b8", dark: "#475569" },
  { id: "Au",  symbol: "Au",  label: "Au",   name: "Gold",           atomicNum: 79,  color: "#eab308", dark: "#a16207" },
  { id: "Hg",  symbol: "Hg",  label: "Hg",   name: "Mercury",        atomicNum: 80,  color: "#94a3b8", dark: "#475569" },
  { id: "Tl",  symbol: "Tl",  label: "Tl",   name: "Thallium",       atomicNum: 81,  color: "#84cc16", dark: "#4d7c0f" },
  { id: "Pb",  symbol: "Pb",  label: "Pb",   name: "Lead",           atomicNum: 82,  color: "#64748b", dark: "#334155" },
  { id: "Bi",  symbol: "Bi",  label: "Bi",   name: "Bismuth",        atomicNum: 83,  color: "#ec4899", dark: "#be185d" },
  { id: "Po",  symbol: "Po",  label: "Po",   name: "Polonium",       atomicNum: 84,  color: "#f97316", dark: "#c2410c" },
  { id: "At",  symbol: "At",  label: "At",   name: "Astatine",       atomicNum: 85,  color: "#7c3aed", dark: "#5b21b6" },
  { id: "Rn",  symbol: "Rn",  label: "Rn",   name: "Radon",          atomicNum: 86,  color: "#94a3b8", dark: "#475569" },
  // Period 7
  { id: "Fr",  symbol: "Fr",  label: "Fr",   name: "Francium",       atomicNum: 87,  color: "#ec4899", dark: "#be185d" },
  { id: "Ra",  symbol: "Ra",  label: "Ra",   name: "Radium",         atomicNum: 88,  color: "#eab308", dark: "#a16207" },
  { id: "Ac",  symbol: "Ac",  label: "Ac",   name: "Actinium",       atomicNum: 89,  color: "#06b6d4", dark: "#0e7490" },
  { id: "Th",  symbol: "Th",  label: "Th",   name: "Thorium",        atomicNum: 90,  color: "#06b6d4", dark: "#0e7490" },
  { id: "Pa",  symbol: "Pa",  label: "Pa",   name: "Protactinium",   atomicNum: 91,  color: "#06b6d4", dark: "#0e7490" },
  { id: "U",   symbol: "U",   label: "U",    name: "Uranium",        atomicNum: 92,  color: "#06b6d4", dark: "#0e7490" },
  { id: "Np",  symbol: "Np",  label: "Np",   name: "Neptunium",      atomicNum: 93,  color: "#06b6d4", dark: "#0e7490" },
  { id: "Pu",  symbol: "Pu",  label: "Pu",   name: "Plutonium",      atomicNum: 94,  color: "#06b6d4", dark: "#0e7490" },
  { id: "Am",  symbol: "Am",  label: "Am",   name: "Americium",      atomicNum: 95,  color: "#06b6d4", dark: "#0e7490" },
  { id: "Cm",  symbol: "Cm",  label: "Cm",   name: "Curium",         atomicNum: 96,  color: "#06b6d4", dark: "#0e7490" },
  { id: "Bk",  symbol: "Bk",  label: "Bk",   name: "Berkelium",      atomicNum: 97,  color: "#06b6d4", dark: "#0e7490" },
  { id: "Cf",  symbol: "Cf",  label: "Cf",   name: "Californium",    atomicNum: 98,  color: "#06b6d4", dark: "#0e7490" },
  { id: "Es",  symbol: "Es",  label: "Es",   name: "Einsteinium",    atomicNum: 99,  color: "#06b6d4", dark: "#0e7490" },
  { id: "Fm",  symbol: "Fm",  label: "Fm",   name: "Fermium",        atomicNum: 100, color: "#06b6d4", dark: "#0e7490" },
  { id: "Md",  symbol: "Md",  label: "Md",   name: "Mendelevium",    atomicNum: 101, color: "#06b6d4", dark: "#0e7490" },
  { id: "No",  symbol: "No",  label: "No",   name: "Nobelium",       atomicNum: 102, color: "#06b6d4", dark: "#0e7490" },
  { id: "Lr",  symbol: "Lr",  label: "Lr",   name: "Lawrencium",     atomicNum: 103, color: "#06b6d4", dark: "#0e7490" },
  { id: "Rf",  symbol: "Rf",  label: "Rf",   name: "Rutherfordium",  atomicNum: 104, color: "#475569", dark: "#1e293b" },
  { id: "Db",  symbol: "Db",  label: "Db",   name: "Dubnium",        atomicNum: 105, color: "#475569", dark: "#1e293b" },
  { id: "Sg",  symbol: "Sg",  label: "Sg",   name: "Seaborgium",     atomicNum: 106, color: "#475569", dark: "#1e293b" },
  { id: "Bh",  symbol: "Bh",  label: "Bh",   name: "Bohrium",        atomicNum: 107, color: "#475569", dark: "#1e293b" },
  { id: "Hs",  symbol: "Hs",  label: "Hs",   name: "Hassium",        atomicNum: 108, color: "#475569", dark: "#1e293b" },
  { id: "Mt",  symbol: "Mt",  label: "Mt",   name: "Meitnerium",     atomicNum: 109, color: "#475569", dark: "#1e293b" },
  { id: "Ds",  symbol: "Ds",  label: "Ds",   name: "Darmstadtium",   atomicNum: 110, color: "#475569", dark: "#1e293b" },
  { id: "Rg",  symbol: "Rg",  label: "Rg",   name: "Roentgenium",    atomicNum: 111, color: "#475569", dark: "#1e293b" },
  { id: "Cn",  symbol: "Cn",  label: "Cn",   name: "Copernicium",    atomicNum: 112, color: "#475569", dark: "#1e293b" },
  { id: "Nh",  symbol: "Nh",  label: "Nh",   name: "Nihonium",       atomicNum: 113, color: "#475569", dark: "#1e293b" },
  { id: "Fl",  symbol: "Fl",  label: "Fl",   name: "Flerovium",      atomicNum: 114, color: "#475569", dark: "#1e293b" },
  { id: "Mc",  symbol: "Mc",  label: "Mc",   name: "Moscovium",      atomicNum: 115, color: "#475569", dark: "#1e293b" },
  { id: "Lv",  symbol: "Lv",  label: "Lv",   name: "Livermorium",    atomicNum: 116, color: "#475569", dark: "#1e293b" },
  { id: "Ts",  symbol: "Ts",  label: "Ts",   name: "Tennessine",     atomicNum: 117, color: "#475569", dark: "#1e293b" },
  { id: "Og",  symbol: "Og",  label: "Og",   name: "Oganesson",      atomicNum: 118, color: "#475569", dark: "#1e293b" },
];

// Keep diatomic aliases for compound recipe matching (H2, O2, N2, Cl2 used in recipes)
export const DIATOMIC_ALIAS = { H2: "H", O2: "O", N2: "N", Cl2: "Cl", Br2: "Br", F2: "F", I2: "I" };

export const COMPOUND_RECIPES = {
  H2O:    { label: "H₂O",    name: "Water",               elements: ["H", "O"],          atomCounts: { H: 2, O: 1 } },
  H2O2:   { label: "H₂O₂",   name: "Hydrogen Peroxide",   elements: ["H", "O"],          atomCounts: { H: 2, O: 2 } },
  CaCO3:  { label: "CaCO₃",  name: "Calcium Carbonate",   elements: ["Ca", "C", "O"],    atomCounts: { Ca: 1, C: 1, O: 3 } },
  HCl:    { label: "HCl",    name: "Hydrochloric Acid",   elements: ["H", "Cl"],         atomCounts: { H: 1, Cl: 1 } },
  CuSO4:  { label: "CuSO₄",  name: "Copper Sulfate",      elements: ["Cu", "S", "O"],    atomCounts: { Cu: 1, S: 1, O: 4 } },
  NaCl:   { label: "NaCl",   name: "Sodium Chloride",     elements: ["Na", "Cl"],        atomCounts: { Na: 1, Cl: 1 } },
  AgNO3:  { label: "AgNO₃",  name: "Silver Nitrate",      elements: ["Ag", "N", "O"],    atomCounts: { Ag: 1, N: 1, O: 3 } },
  NaOH:   { label: "NaOH",   name: "Sodium Hydroxide",    elements: ["Na", "O", "H"],    atomCounts: { Na: 1, O: 1, H: 1 } },
  CH4:    { label: "CH₄",    name: "Methane",             elements: ["C", "H"],          atomCounts: { C: 1, H: 4 } },
  C3H8:   { label: "C₃H₈",   name: "Propane",             elements: ["C", "H"],          atomCounts: { C: 3, H: 8 } },
  // Distractors
  CO2:    { label: "CO₂",    name: "Carbon Dioxide",      elements: ["C", "O"],          atomCounts: { C: 1, O: 2 } },
  MgO:    { label: "MgO",    name: "Magnesium Oxide",     elements: ["Mg", "O"],         atomCounts: { Mg: 1, O: 1 } },
  CaO:    { label: "CaO",    name: "Calcium Oxide",       elements: ["Ca", "O"],         atomCounts: { Ca: 1, O: 1 } },
  Na2CO3: { label: "Na₂CO₃", name: "Sodium Carbonate",    elements: ["Na", "C", "O"],    atomCounts: { Na: 2, C: 1, O: 3 } },
  H2SO4:  { label: "H₂SO₄",  name: "Sulfuric Acid",       elements: ["H", "S", "O"],     atomCounts: { H: 2, S: 1, O: 4 } },
  HNO3:   { label: "HNO₃",   name: "Nitric Acid",         elements: ["H", "N", "O"],     atomCounts: { H: 1, N: 1, O: 3 } }
};


