export const REACTIONS = [
  // ── COMBINATION ──────────────────────────────────────────────────────────
  {
    id: "comb-1",
    type: "combination",
    question: "Hydrogen gas burns in the presence of oxygen to form water. Which reactants do you need?",
    hint: "Look for the gas that is the most abundant element in the universe, and the gas we breathe to survive.",
    equation: { reactants: ["H₂", "O"], arrow: "→", products: ["H₂O"], balanced: "H₂ + O → H₂O" },
    correctReactants: ["H2", "O"],
    inventory: [
      { id: "H2",  label: "H₂",   name: "Hydrogen Gas",    color: "#0ea5e9", dark: "#0369a1" },
      { id: "O",   label: "O",    name: "Oxygen",          color: "#f43f5e", dark: "#be123c" },
      { id: "O2",  label: "O₂",   name: "Oxygen Gas",      color: "#ef4444", dark: "#b91c1c" },
      { id: "N2",  label: "N₂",   name: "Nitrogen Gas",    color: "#64748b", dark: "#334155" },
      { id: "CO2", label: "CO₂",  name: "Carbon Dioxide",  color: "#6b7280", dark: "#374151" },
      { id: "Cl2", label: "Cl₂",  name: "Chlorine Gas",    color: "#9333ea", dark: "#6b21a8" },
    ],
    explanation: {
      summary: "Water Synthesis — Combination Reaction",
      mechanism: [
        "Hydrogen (H₂) and Oxygen (O) are both diatomic molecules in their elemental form.",
        "When ignited, the strong H–H and O=O bonds break. The hydrogen and oxygen atoms re-bond with each other.",
        "Each oxygen atom shares electrons with two hydrogen atoms, forming two O–H covalent bonds.",
        "The product, H₂O (water), is a polar molecule where oxygen pulls electron density toward itself.",
        "The reaction is highly exothermic — it releases about 286 kJ per mole of water formed.",
        "Balanced equation: 2H₂ + O₂ → 2H₂O",
      ],
      realWorld: "This reaction powers hydrogen fuel cells in zero-emission vehicles and rockets.",
      energyType: "Exothermic",
    },
  },
  {
    id: "comb-2",
    type: "combination",
    question: "Magnesium ribbon burns with a brilliant white flame in air. What two substances combine?",
    hint: "The metal in 'magnesium ribbon' plus the gas it burns in.",
    equation: { reactants: ["Mg", "O₂"], arrow: "→", products: ["MgO"], balanced: "2Mg + O₂ → 2MgO" },
    correctReactants: ["Mg", "O2"],
    inventory: [
      { id: "Mg",  label: "Mg",   name: "Magnesium",      color: "#84cc16", dark: "#4d7c0f" },
      { id: "O2",  label: "O₂",   name: "Oxygen Gas",     color: "#ef4444", dark: "#b91c1c" },
      { id: "Ca",  label: "Ca",   name: "Calcium",        color: "#eab308", dark: "#a16207" },
      { id: "H2",  label: "H₂",   name: "Hydrogen Gas",   color: "#0ea5e9", dark: "#0369a1" },
      { id: "S",   label: "S",    name: "Sulfur",         color: "#f59e0b", dark: "#b45309" },
    ],
    explanation: {
      summary: "Magnesium Oxide Formation — Combination Reaction",
      mechanism: [
        "Magnesium (Mg) is an alkaline earth metal with two electrons in its outer shell.",
        "When heated, Mg atoms lose these 2 electrons easily to become Mg²⁺ ions.",
        "Oxygen (O₂) gains 2 electrons per atom to become O²⁻ ions.",
        "The oppositely charged ions attract each other strongly, forming the ionic compound MgO.",
        "The reaction produces a dazzling white light because the burning temperature (~1900°C) causes the MgO particles to emit white light.",
        "Balanced equation: 2Mg + O₂ → 2MgO",
      ],
      realWorld: "MgO (magnesia) is used in antacids, refractory bricks, and fireproofing materials.",
      energyType: "Exothermic",
    },
  },
  {
    id: "comb-3",
    type: "combination",
    question: "Sodium metal reacts vigorously with chlorine gas to form table salt. Select the reactants.",
    hint: "An alkali metal and a halogen gas combine to form a famous seasoning.",
    equation: { reactants: ["Na", "Cl₂"], arrow: "→", products: ["NaCl"], balanced: "2Na + Cl₂ → 2NaCl" },
    correctReactants: ["Na", "Cl2"],
    inventory: [
      { id: "Na",  label: "Na",   name: "Sodium",         color: "#f97316", dark: "#c2410c" },
      { id: "Cl2", label: "Cl₂",  name: "Chlorine Gas",   color: "#9333ea", dark: "#6b21a8" },
      { id: "K",   label: "K",    name: "Potassium",      color: "#ec4899", dark: "#be185d" },
      { id: "Br2", label: "Br₂",  name: "Bromine",        color: "#f43f5e", dark: "#be123c" },
      { id: "O2",  label: "O₂",   name: "Oxygen Gas",     color: "#ef4444", dark: "#b91c1c" },
    ],
    explanation: {
      summary: "Sodium Chloride (Table Salt) Formation — Combination Reaction",
      mechanism: [
        "Sodium (Na) is a soft, highly reactive metal with one electron in its outermost shell.",
        "Chlorine (Cl₂) is a diatomic halogen that strongly attracts electrons (high electronegativity).",
        "Sodium transfers its outer electron to a chlorine atom: Na → Na⁺ + e⁻",
        "Chlorine accepts the electron: Cl + e⁻ → Cl⁻",
        "The Na⁺ and Cl⁻ ions arrange into a stable cubic crystal lattice held by strong ionic bonds.",
        "Balanced equation: 2Na + Cl₂ → 2NaCl",
      ],
      realWorld: "NaCl (table salt) is essential for human biology, food preservation, and road de-icing.",
      energyType: "Exothermic",
    },
  },

  // ── DECOMPOSITION ─────────────────────────────────────────────────────────
  {
    id: "decomp-1",
    type: "decomposition",
    question: "When water is electrolysed (electric current passed through it), it splits into two gases. What is the starting compound?",
    hint: "The universal solvent splits into the gases that make it up.",
    equation: { reactants: ["H₂O"], arrow: "→", products: ["H₂", "O₂"], balanced: "2H₂O → 2H₂ + O₂" },
    correctReactants: ["H2O"],
    inventory: [
      { id: "H2O",  label: "H₂O",  name: "Water",           color: "#0ea5e9", dark: "#0369a1" },
      { id: "NaCl", label: "NaCl", name: "Sodium Chloride",  color: "#f97316", dark: "#c2410c" },
      { id: "H2O2", label: "H₂O₂", name: "Hydrogen Peroxide",color: "#8b5cf6", dark: "#6d28d9" },
      { id: "CO2",  label: "CO₂",  name: "Carbon Dioxide",   color: "#6b7280", dark: "#374151" },
    ],
    explanation: {
      summary: "Electrolysis of Water — Decomposition Reaction",
      mechanism: [
        "Water (H₂O) is a stable covalent molecule, but it can be broken apart by supplying electrical energy.",
        "At the negative electrode (cathode): 2H⁺ + 2e⁻ → H₂ (hydrogen gas bubbles form).",
        "At the positive electrode (anode): 2H₂O → O₂ + 4H⁺ + 4e⁻ (oxygen gas bubbles form).",
        "Twice as much hydrogen is produced as oxygen (2:1 volume ratio) due to the formula H₂O.",
        "This is an endothermic reaction — electrical energy must be continuously supplied to drive it.",
        "Balanced equation: 2H₂O → 2H₂ + O₂",
      ],
      realWorld: "Electrolysis of water is used to produce 'green hydrogen' fuel for clean energy systems.",
      energyType: "Endothermic",
    },
  },
  {
    id: "decomp-2",
    type: "decomposition",
    question: "Limestone (calcium carbonate) decomposes when strongly heated in a kiln. Select the starting compound.",
    hint: "The white rock used in construction that fizzes with acid and breaks down in a kiln.",
    equation: { reactants: ["CaCO₃"], arrow: "→", products: ["CaO", "CO₂"], balanced: "CaCO₃ → CaO + CO₂" },
    correctReactants: ["CaCO3"],
    inventory: [
      { id: "CaCO3", label: "CaCO₃", name: "Calcium Carbonate (Limestone)", color: "#eab308", dark: "#a16207" },
      { id: "CaO",   label: "CaO",   name: "Calcium Oxide (Quicklime)",     color: "#f97316", dark: "#c2410c" },
      { id: "MgO",   label: "MgO",   name: "Magnesium Oxide",               color: "#84cc16", dark: "#4d7c0f" },
      { id: "Na2CO3",label: "Na₂CO₃",name: "Sodium Carbonate",              color: "#f97316", dark: "#c2410c" },
    ],
    explanation: {
      summary: "Thermal Decomposition of Limestone — Decomposition Reaction",
      mechanism: [
        "Calcium carbonate (CaCO₃) has strong ionic bonds between Ca²⁺ and CO₃²⁻ ions.",
        "Heating to ~900°C provides enough energy to break the Ca–O bonds in the carbonate.",
        "The carbonate ion (CO₃²⁻) loses an oxygen atom and releases carbon dioxide gas (CO₂).",
        "The remaining calcium and oxygen form calcium oxide (CaO), also called quicklime.",
        "This is an endothermic reaction — sustained high temperature is required.",
        "Balanced equation: CaCO₃ → CaO + CO₂",
      ],
      realWorld: "This process (called 'calcination') is the first step in making cement, lime mortar, and steel.",
      energyType: "Endothermic",
    },
  },
  {
    id: "decomp-3",
    type: "decomposition",
    question: "Hydrogen peroxide stored in a medicine cabinet slowly decomposes into water and oxygen. Select the reactant.",
    hint: "The antiseptic liquid in brown bottles that fizzes when poured on a wound.",
    equation: { reactants: ["H₂O₂"], arrow: "→", products: ["H₂O", "O₂"], balanced: "2H₂O₂ → 2H₂O + O₂" },
    correctReactants: ["H2O2"],
    inventory: [
      { id: "H2O2", label: "H₂O₂", name: "Hydrogen Peroxide", color: "#8b5cf6", dark: "#6d28d9" },
      { id: "H2O",  label: "H₂O",  name: "Water",             color: "#0ea5e9", dark: "#0369a1" },
      { id: "NaOH", label: "NaOH", name: "Sodium Hydroxide",  color: "#f97316", dark: "#c2410c" },
      { id: "KMnO4",label: "KMnO₄",name: "Potassium Permanganate", color: "#a855f7", dark: "#7e22ce" },
    ],
    explanation: {
      summary: "Decomposition of Hydrogen Peroxide",
      mechanism: [
        "Hydrogen peroxide (H₂O₂) is an unstable molecule — it has an O–O single bond that is weak and easily broken.",
        "Even at room temperature, H₂O₂ slowly decomposes. Catalysts (like MnO₂ or enzymes) speed this up dramatically.",
        "The O–O bond breaks: each H₂O₂ splits into H₂O and a free oxygen atom.",
        "Two free oxygen atoms combine: O + O → O₂ (oxygen gas is released as bubbles).",
        "The fizzing you see on a wound is oxygen gas being released — it helps clean the wound.",
        "Balanced equation: 2H₂O₂ → 2H₂O + O₂",
      ],
      realWorld: "Catalytic decomposition of H₂O₂ is used in rocket propulsion (monopropellant thrusters).",
      energyType: "Exothermic",
    },
  },

  // ── SINGLE DISPLACEMENT ───────────────────────────────────────────────────
  {
    id: "single-1",
    type: "single_displacement",
    question: "Zinc metal is dropped into hydrochloric acid. Zinc displaces hydrogen gas from the acid. Select both reactants.",
    hint: "A metal from group 12 meets a very common strong acid.",
    equation: { reactants: ["Zn", "HCl"], arrow: "→", products: ["ZnCl₂", "H₂"], balanced: "Zn + 2HCl → ZnCl₂ + H₂" },
    correctReactants: ["Zn", "HCl"],
    inventory: [
      { id: "Zn",  label: "Zn",  name: "Zinc",              color: "#0891b2", dark: "#0e7490" },
      { id: "HCl", label: "HCl", name: "Hydrochloric Acid",  color: "#65a30d", dark: "#3f6212" },
      { id: "Fe",  label: "Fe",  name: "Iron",               color: "#78716c", dark: "#44403c" },
      { id: "H2SO4",label:"H₂SO₄",name: "Sulfuric Acid",     color: "#dc2626", dark: "#991b1b" },
      { id: "Cu",  label: "Cu",  name: "Copper",             color: "#d97706", dark: "#92400e" },
    ],
    explanation: {
      summary: "Zinc + Hydrochloric Acid — Single Displacement Reaction",
      mechanism: [
        "Zinc (Zn) is higher in the metal activity series than hydrogen (H), so it can displace hydrogen from acids.",
        "HCl dissociates in water into H⁺ and Cl⁻ ions.",
        "Zinc atoms lose 2 electrons each: Zn → Zn²⁺ + 2e⁻ (oxidation).",
        "Two H⁺ ions each gain 1 electron: 2H⁺ + 2e⁻ → H₂ (reduction). This is a redox reaction.",
        "Zn²⁺ combines with 2 Cl⁻ ions to form zinc chloride (ZnCl₂), which dissolves in solution.",
        "You can observe bubbling as hydrogen gas (H₂) is released.",
        "Balanced equation: Zn + 2HCl → ZnCl₂ + H₂",
      ],
      realWorld: "This reaction is used in labs to generate pure hydrogen gas and in galvanizing steel with zinc.",
      energyType: "Exothermic",
    },
  },
  {
    id: "single-2",
    type: "single_displacement",
    question: "An iron nail placed in copper sulfate solution turns copper-coloured. Iron displaces copper. Select both reactants.",
    hint: "A common metal nail meets a blue crystal solution.",
    equation: { reactants: ["Fe", "CuSO₄"], arrow: "→", products: ["FeSO₄", "Cu"], balanced: "Fe + CuSO₄ → FeSO₄ + Cu" },
    correctReactants: ["Fe", "CuSO4"],
    inventory: [
      { id: "Fe",   label: "Fe",    name: "Iron",              color: "#78716c", dark: "#44403c" },
      { id: "CuSO4",label: "CuSO₄", name: "Copper Sulfate",    color: "#0891b2", dark: "#0e7490" },
      { id: "Cu",   label: "Cu",    name: "Copper",            color: "#d97706", dark: "#92400e" },
      { id: "Zn",   label: "Zn",    name: "Zinc",              color: "#0891b2", dark: "#0e7490" },
      { id: "AgNO3",label: "AgNO₃", name: "Silver Nitrate",    color: "#94a3b8", dark: "#475569" },
    ],
    explanation: {
      summary: "Iron + Copper Sulfate — Single Displacement Reaction",
      mechanism: [
        "Iron (Fe) is more reactive than copper (Cu) and sits higher in the electrochemical activity series.",
        "CuSO₄ is an ionic compound — Cu²⁺ and SO₄²⁻ ions exist in solution (the blue colour comes from Cu²⁺).",
        "Iron atoms give up 2 electrons: Fe → Fe²⁺ + 2e⁻ (iron is oxidised).",
        "Cu²⁺ ions accept those 2 electrons: Cu²⁺ + 2e⁻ → Cu (copper is reduced).",
        "The copper metal deposits onto the iron surface — that's the copper coating you see!",
        "The solution turns from blue to pale green as Cu²⁺ is replaced by Fe²⁺.",
        "Balanced equation: Fe + CuSO₄ → FeSO₄ + Cu",
      ],
      realWorld: "This principle is used in electroplating, metal recovery from mining waste, and electrochemical cells.",
      energyType: "Exothermic",
    },
  },

  // ── DOUBLE DISPLACEMENT ───────────────────────────────────────────────────
  {
    id: "double-1",
    type: "double_displacement",
    question: "Mixing sodium chloride solution with silver nitrate solution forms a white precipitate of silver chloride. Select both reactants.",
    hint: "Table salt solution meets a silver compound solution — the ions swap partners.",
    equation: { reactants: ["NaCl", "AgNO₃"], arrow: "→", products: ["AgCl↓", "NaNO₃"], balanced: "NaCl + AgNO₃ → AgCl↓ + NaNO₃" },
    correctReactants: ["NaCl", "AgNO3"],
    inventory: [
      { id: "NaCl",  label: "NaCl",  name: "Sodium Chloride",  color: "#f97316", dark: "#c2410c" },
      { id: "AgNO3", label: "AgNO₃", name: "Silver Nitrate",   color: "#94a3b8", dark: "#475569" },
      { id: "KCl",   label: "KCl",   name: "Potassium Chloride",color: "#ec4899", dark: "#be185d" },
      { id: "NaOH",  label: "NaOH",  name: "Sodium Hydroxide", color: "#f97316", dark: "#c2410c" },
      { id: "HNO3",  label: "HNO₃",  name: "Nitric Acid",      color: "#dc2626", dark: "#991b1b" },
    ],
    explanation: {
      summary: "Silver Chloride Precipitation — Double Displacement Reaction",
      mechanism: [
        "NaCl and AgNO₃ are both ionic compounds that dissociate completely in water.",
        "In solution: Na⁺, Cl⁻, Ag⁺, and NO₃⁻ ions are all present.",
        "Ag⁺ and Cl⁻ are strongly attracted to each other — AgCl is almost completely insoluble in water.",
        "The Ag⁺ and Cl⁻ ions come together and crash out of solution as a white solid (precipitate).",
        "Na⁺ and NO₃⁻ remain in solution as 'spectator ions' — they don't participate in the reaction.",
        "Net ionic equation: Ag⁺(aq) + Cl⁻(aq) → AgCl(s)↓",
        "Balanced equation: NaCl + AgNO₃ → AgCl↓ + NaNO₃",
      ],
      realWorld: "This reaction is the basis for classical silver-based photography and is used in lab tests for chloride ions.",
      energyType: "Exothermic (slight)",
    },
  },
  {
    id: "double-2",
    type: "double_displacement",
    question: "Hydrochloric acid reacts with sodium hydroxide in a neutralisation reaction. Select both reactants.",
    hint: "A strong acid meets a strong base — they neutralise each other to form salt and water.",
    equation: { reactants: ["HCl", "NaOH"], arrow: "→", products: ["NaCl", "H₂O"], balanced: "HCl + NaOH → NaCl + H₂O" },
    correctReactants: ["HCl", "NaOH"],
    inventory: [
      { id: "HCl",   label: "HCl",  name: "Hydrochloric Acid", color: "#65a30d", dark: "#3f6212" },
      { id: "NaOH",  label: "NaOH", name: "Sodium Hydroxide",  color: "#f97316", dark: "#c2410c" },
      { id: "H2SO4", label: "H₂SO₄",name: "Sulfuric Acid",     color: "#dc2626", dark: "#991b1b" },
      { id: "KOH",   label: "KOH",  name: "Potassium Hydroxide",color: "#ec4899", dark: "#be185d" },
      { id: "NaCl",  label: "NaCl", name: "Sodium Chloride",   color: "#f97316", dark: "#c2410c" },
    ],
    explanation: {
      summary: "Acid-Base Neutralisation — Double Displacement Reaction",
      mechanism: [
        "HCl is a strong acid — it fully dissociates in water: HCl → H⁺ + Cl⁻.",
        "NaOH is a strong base — it fully dissociates in water: NaOH → Na⁺ + OH⁻.",
        "The key event is H⁺ combining with OH⁻: H⁺ + OH⁻ → H₂O (water is formed).",
        "Na⁺ and Cl⁻ remain in solution and form NaCl (sodium chloride/salt) when the water evaporates.",
        "The reaction releases heat — it is exothermic. The temperature of the solution rises.",
        "Net ionic equation: H⁺(aq) + OH⁻(aq) → H₂O(l)",
        "Balanced equation: HCl + NaOH → NaCl + H₂O",
      ],
      realWorld: "Neutralisation is used in antacids (base neutralises stomach acid), treating acidic soil with lime, and industrial wastewater treatment.",
      energyType: "Exothermic",
    },
  },

  // ── COMBUSTION ────────────────────────────────────────────────────────────
  {
    id: "combust-1",
    type: "combustion",
    question: "Natural gas (methane) burns in a gas stove. It reacts with oxygen to produce carbon dioxide and water vapour. Select the two reactants.",
    hint: "The fuel that heats your home stove plus the gas it requires to burn.",
    equation: { reactants: ["CH₄", "O₂"], arrow: "→", products: ["CO₂", "H₂O"], balanced: "CH₄ + 2O₂ → CO₂ + 2H₂O" },
    correctReactants: ["CH4", "O2"],
    inventory: [
      { id: "CH4", label: "CH₄", name: "Methane (Natural Gas)", color: "#0891b2", dark: "#0e7490" },
      { id: "O2",  label: "O₂",  name: "Oxygen Gas",            color: "#ef4444", dark: "#b91c1c" },
      { id: "CO2", label: "CO₂", name: "Carbon Dioxide",        color: "#6b7280", dark: "#374151" },
      { id: "C3H8",label: "C₃H₈",name: "Propane",               color: "#d97706", dark: "#92400e" },
      { id: "N2",  label: "N₂",  name: "Nitrogen Gas",          color: "#64748b", dark: "#334155" },
    ],
    explanation: {
      summary: "Combustion of Methane — Combustion Reaction",
      mechanism: [
        "Methane (CH₄) is the simplest hydrocarbon — one carbon bonded to four hydrogen atoms.",
        "Combustion begins when methane is ignited (spark or flame provides activation energy).",
        "Oxygen breaks apart the C–H bonds in methane. Carbon atoms bond with 2 oxygen atoms → CO₂.",
        "Hydrogen atoms bond with oxygen atoms → H₂O (water vapour).",
        "This is a highly exothermic chain reaction — each step releases energy that drives the next.",
        "Complete combustion requires sufficient oxygen. If O₂ is limited, carbon monoxide (CO) — a toxic gas — is produced instead.",
        "Balanced equation: CH₄ + 2O₂ → CO₂ + 2H₂O",
      ],
      realWorld: "Methane combustion powers gas stoves, heating systems, and natural gas power plants. It releases ~890 kJ/mol of energy.",
      energyType: "Exothermic",
    },
  },
  {
    id: "combust-2",
    type: "combustion",
    question: "Propane gas in a BBQ grill burns with oxygen to produce heat, carbon dioxide, and water. Select the two reactants.",
    hint: "The fuel in portable gas cylinders meets the gas needed for any fire.",
    equation: { reactants: ["C₃H₈", "O₂"], arrow: "→", products: ["CO₂", "H₂O"], balanced: "C₃H₈ + 5O₂ → 3CO₂ + 4H₂O" },
    correctReactants: ["C3H8", "O2"],
    inventory: [
      { id: "C3H8", label: "C₃H₈", name: "Propane",           color: "#d97706", dark: "#92400e" },
      { id: "O2",   label: "O₂",   name: "Oxygen Gas",        color: "#ef4444", dark: "#b91c1c" },
      { id: "CH4",  label: "CH₄",  name: "Methane",           color: "#0891b2", dark: "#0e7490" },
      { id: "CO2",  label: "CO₂",  name: "Carbon Dioxide",    color: "#6b7280", dark: "#374151" },
      { id: "H2O",  label: "H₂O",  name: "Water",             color: "#0ea5e9", dark: "#0369a1" },
    ],
    explanation: {
      summary: "Combustion of Propane — Combustion Reaction",
      mechanism: [
        "Propane (C₃H₈) is a 3-carbon hydrocarbon commonly used as a portable fuel.",
        "When ignited, propane reacts vigorously with oxygen in a chain reaction.",
        "Each carbon atom in propane is fully oxidised to CO₂: C + O₂ → CO₂.",
        "Each pair of hydrogen atoms is oxidised to water: 2H + ½O₂ → H₂O.",
        "The reaction needs 5 molecules of O₂ for every 1 molecule of C₃H₈ — oxygen must be in good supply.",
        "The energy released (~2220 kJ/mol) appears as heat and the blue/orange flame you see.",
        "Balanced equation: C₃H₈ + 5O₂ → 3CO₂ + 4H₂O",
      ],
      realWorld: "Propane is used in BBQ grills, camping stoves, forklifts, and as a heating fuel in rural areas without gas pipelines.",
      energyType: "Exothermic",
    },
  },
    // ── ADDITIONAL COMBINATION ──────────────────────────────────────────────
  {
    id: "comb-4",
    type: "combination",
    question: "Calcium metal reacts with oxygen in the air to form a white solid used in cement. Select the reactants.",
    hint: "An alkaline earth metal combines with the gas that makes up 21% of air.",
    equation: { reactants: ["Ca", "O₂"], arrow: "→", products: ["CaO"], balanced: "2Ca + O₂ → 2CaO" },
    correctReactants: ["Ca", "O2"],
    inventory: [
      { id: "Ca",  label: "Ca",   name: "Calcium",        color: "#eab308", dark: "#a16207" },
      { id: "O2",  label: "O₂",   name: "Oxygen Gas",     color: "#ef4444", dark: "#b91c1c" },
      { id: "Mg",  label: "Mg",   name: "Magnesium",      color: "#84cc16", dark: "#4d7c0f" },
      { id: "N2",  label: "N₂",   name: "Nitrogen Gas",   color: "#64748b", dark: "#334155" },
      { id: "CO2", label: "CO₂",  name: "Carbon Dioxide", color: "#6b7280", dark: "#374151" },
    ],
    explanation: {
      summary: "Calcium Oxide Formation — Combination Reaction",
      mechanism: [
        "Calcium (Ca) is an alkaline earth metal with two valence electrons in its outer shell.",
        "When exposed to air, calcium readily loses these electrons to oxygen atoms.",
        "Each calcium atom becomes Ca²⁺ and each oxygen atom becomes O²⁻.",
        "The oppositely charged ions attract strongly, forming the ionic lattice of CaO.",
        "This reaction is highly exothermic and calcium must be stored under oil to prevent it.",
        "Balanced equation: 2Ca + O₂ → 2CaO",
      ],
      realWorld: "CaO (quicklime) is essential in steelmaking, water treatment, and as a key ingredient in cement.",
      energyType: "Exothermic",
    },
  },
  {
    id: "comb-5",
    type: "combination",
    question: "Sulfur powder burns in oxygen with a blue flame to form a choking gas. Select the reactants.",
    hint: "A yellow non-metal burns in air to produce the gas that smells like rotten eggs when mixed with water.",
    equation: { reactants: ["S", "O₂"], arrow: "→", products: ["SO₂"], balanced: "S + O₂ → SO₂" },
    correctReactants: ["S", "O2"],
    inventory: [
      { id: "S",   label: "S",    name: "Sulfur",         color: "#f59e0b", dark: "#b45309" },
      { id: "O2",  label: "O₂",   name: "Oxygen Gas",     color: "#ef4444", dark: "#b91c1c" },
      { id: "P",   label: "P",    name: "Phosphorus",     color: "#f97316", dark: "#c2410c" },
      { id: "N2",  label: "N₂",   name: "Nitrogen Gas",   color: "#64748b", dark: "#334155" },
      { id: "C",   label: "C",    name: "Carbon",         color: "#374151", dark: "#1f2937" },
    ],
    explanation: {
      summary: "Sulfur Dioxide Formation — Combination Reaction",
      mechanism: [
        "Sulfur (S) exists as S₈ rings at room temperature — eight sulfur atoms bonded in a ring.",
        "When heated, the S₈ rings break apart into individual sulfur atoms.",
        "Each sulfur atom reacts with one O₂ molecule to form SO₂.",
        "The reaction produces a characteristic blue flame and a choking, pungent gas.",
        "SO₂ is a bent molecule with a bond angle of ~119° due to lone pair repulsion.",
        "Balanced equation: S + O₂ → SO₂",
      ],
      realWorld: "SO₂ is used as a preservative in dried fruits, in wine making, and is a major air pollutant from burning fossil fuels.",
      energyType: "Exothermic",
    },
  },

  // ── ADDITIONAL DECOMPOSITION ────────────────────────────────────────────
  {
    id: "decomp-4",
    type: "decomposition",
    question: "Mercury(II) oxide breaks down when heated, producing liquid mercury and oxygen gas. Select the starting compound.",
    hint: "A red or orange powder that was used in old thermometers — it decomposes into a shiny liquid metal and a gas.",
    equation: { reactants: ["HgO"], arrow: "→", products: ["Hg", "O₂"], balanced: "2HgO → 2Hg + O₂" },
    correctReactants: ["HgO"],
    inventory: [
      { id: "HgO",  label: "HgO",  name: "Mercury(II) Oxide", color: "#f97316", dark: "#c2410c" },
      { id: "H2O2", label: "H₂O₂", name: "Hydrogen Peroxide", color: "#8b5cf6", dark: "#6d28d9" },
      { id: "CaCO3",label: "CaCO₃",name: "Calcium Carbonate", color: "#eab308", dark: "#a16207" },
      { id: "NaCl", label: "NaCl", name: "Sodium Chloride",   color: "#f97316", dark: "#c2410c" },
    ],
    explanation: {
      summary: "Thermal Decomposition of Mercury(II) Oxide",
      mechanism: [
        "Mercury(II) oxide (HgO) is a red or orange solid with ionic bonds between Hg²⁺ and O²⁻.",
        "When heated to ~500°C, thermal energy overcomes the lattice energy holding the ions together.",
        "The compound splits: mercury ions gain electrons and form liquid mercury metal (Hg).",
        "Oxygen ions lose electrons and combine to form O₂ gas, which can relight a glowing splint.",
        "This was one of the reactions used by Joseph Priestley to discover oxygen in 1774.",
        "Balanced equation: 2HgO → 2Hg + O₂",
      ],
      realWorld: "This reaction was historically important in the discovery of oxygen; mercury is now avoided due to toxicity.",
      energyType: "Endothermic",
    },
  },
  {
    id: "decomp-5",
    type: "decomposition",
    question: "Potassium chlorate decomposes when heated with manganese dioxide catalyst, producing potassium chloride and oxygen. Select the reactant.",
    hint: "A white crystalline compound used in matches and fireworks — it breaks down to release oxygen for breathing apparatus.",
    equation: { reactants: ["KClO₃"], arrow: "→", products: ["KCl", "O₂"], balanced: "2KClO₃ → 2KCl + 3O₂" },
    correctReactants: ["KClO3"],
    inventory: [
      { id: "KClO3", label: "KClO₃", name: "Potassium Chlorate", color: "#ec4899", dark: "#be185d" },
      { id: "H2O",   label: "H₂O",   name: "Water",              color: "#0ea5e9", dark: "#0369a1" },
      { id: "NaOH",  label: "NaOH",  name: "Sodium Hydroxide",   color: "#f97316", dark: "#c2410c" },
      { id: "CaCO3", label: "CaCO₃", name: "Calcium Carbonate",  color: "#eab308", dark: "#a16207" },
    ],
    explanation: {
      summary: "Thermal Decomposition of Potassium Chlorate",
      mechanism: [
        "Potassium chlorate (KClO₃) contains the chlorate ion (ClO₃⁻) with oxygen tightly bound to chlorine.",
        "Heating alone causes slow decomposition, but MnO₂ catalyst dramatically speeds it up.",
        "The catalyst lowers the activation energy, allowing the reaction to proceed at ~200°C instead of ~400°C.",
        "The ClO₃⁻ ion breaks apart: chlorine stays as Cl⁻ in KCl, while oxygen is released as O₂ gas.",
        "The oxygen gas produced can relight a glowing splint — a classic test for oxygen.",
        "Balanced equation: 2KClO₃ → 2KCl + 3O₂",
      ],
      realWorld: "Used in emergency oxygen generators for aircraft and spacecraft, and in fireworks as an oxidiser.",
      energyType: "Endothermic",
    },
  },

  // ── ADDITIONAL SINGLE DISPLACEMENT ──────────────────────────────────────
  {
    id: "single-3",
    type: "single_displacement",
    question: "Aluminium foil is placed in copper(II) chloride solution. Aluminium displaces copper, producing a reddish-brown coating. Select both reactants.",
    hint: "A lightweight silvery metal from group 13 displaces a reddish metal from its blue solution.",
    equation: { reactants: ["Al", "CuCl₂"], arrow: "→", products: ["AlCl₃", "Cu"], balanced: "2Al + 3CuCl₂ → 2AlCl₃ + 3Cu" },
    correctReactants: ["Al", "CuCl2"],
    inventory: [
      { id: "Al",    label: "Al",    name: "Aluminium",        color: "#94a3b8", dark: "#475569" },
      { id: "CuCl2", label: "CuCl₂", name: "Copper(II) Chloride", color: "#0891b2", dark: "#0e7490" },
      { id: "Fe",    label: "Fe",    name: "Iron",             color: "#78716c", dark: "#44403c" },
      { id: "Zn",    label: "Zn",    name: "Zinc",             color: "#0891b2", dark: "#0e7490" },
      { id: "AgNO3", label: "AgNO₃", name: "Silver Nitrate",   color: "#94a3b8", dark: "#475569" },
    ],
    explanation: {
      summary: "Aluminium + Copper(II) Chloride — Single Displacement Reaction",
      mechanism: [
        "Aluminium (Al) is higher in the activity series than copper (Cu) and has a strong tendency to lose 3 electrons.",
        "CuCl₂ dissociates in water into Cu²⁺ (blue) and Cl⁻ ions.",
        "Each Al atom loses 3 electrons: Al → Al³⁺ + 3e⁻ (oxidation).",
        "Cu²⁺ ions gain 2 electrons each: Cu²⁺ + 2e⁻ → Cu (reduction).",
        "The copper metal deposits as a reddish-brown solid on the aluminium surface.",
        "The blue colour fades as Cu²⁺ is replaced by colourless Al³⁺ ions in solution.",
        "Balanced equation: 2Al + 3CuCl₂ → 2AlCl₃ + 3Cu",
      ],
      realWorld: "This principle is used in thermite reactions, aluminium extraction, and understanding corrosion protection.",
      energyType: "Exothermic",
    },
  },
  {
    id: "single-4",
    type: "single_displacement",
    question: "Magnesium ribbon reacts with dilute sulfuric acid, displacing hydrogen gas. Select both reactants.",
    hint: "A reactive alkaline earth metal meets a strong diprotic acid — bubbles of gas form rapidly.",
    equation: { reactants: ["Mg", "H₂SO₄"], arrow: "→", products: ["MgSO₄", "H₂"], balanced: "Mg + H₂SO₄ → MgSO₄ + H₂" },
    correctReactants: ["Mg", "H2SO4"],
    inventory: [
      { id: "Mg",    label: "Mg",    name: "Magnesium",       color: "#84cc16", dark: "#4d7c0f" },
      { id: "H2SO4", label: "H₂SO₄", name: "Sulfuric Acid",   color: "#dc2626", dark: "#991b1b" },
      { id: "Zn",    label: "Zn",    name: "Zinc",            color: "#0891b2", dark: "#0e7490" },
      { id: "HCl",   label: "HCl",   name: "Hydrochloric Acid", color: "#65a30d", dark: "#3f6212" },
      { id: "Cu",    label: "Cu",    name: "Copper",          color: "#d97706", dark: "#92400e" },
    ],
    explanation: {
      summary: "Magnesium + Sulfuric Acid — Single Displacement Reaction",
      mechanism: [
        "Magnesium (Mg) is highly reactive and readily loses its 2 valence electrons.",
        "Sulfuric acid (H₂SO₄) is a strong acid that fully dissociates: H₂SO₄ → 2H⁺ + SO₄²⁻.",
        "Mg atoms lose 2 electrons: Mg → Mg²⁺ + 2e⁻ (oxidation).",
        "Two H⁺ ions each gain 1 electron: 2H⁺ + 2e⁻ → H₂ (reduction).",
        "Mg²⁺ combines with SO₄²⁻ to form magnesium sulfate (MgSO₄), which dissolves in water.",
        "Vigorous bubbling occurs as hydrogen gas is rapidly evolved — the reaction is quite exothermic.",
        "Balanced equation: Mg + H₂SO₄ → MgSO₄ + H₂",
      ],
      realWorld: "Magnesium sulfate (Epsom salt) is used in medicine and agriculture; this reaction generates hydrogen in labs.",
      energyType: "Exothermic",
    },
  },

  // ── ADDITIONAL DOUBLE DISPLACEMENT ──────────────────────────────────────
  {
    id: "double-3",
    type: "double_displacement",
    question: "Barium chloride solution reacts with sodium sulfate solution to form a white precipitate of barium sulfate. Select both reactants.",
    hint: "A toxic heavy metal salt meets a common sulfate — the heavy metal forms an insoluble white solid used in X-rays.",
    equation: { reactants: ["BaCl₂", "Na₂SO₄"], arrow: "→", products: ["BaSO₄↓", "NaCl"], balanced: "BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl" },
    correctReactants: ["BaCl2", "Na2SO4"],
    inventory: [
      { id: "BaCl2",  label: "BaCl₂",  name: "Barium Chloride",  color: "#a855f7", dark: "#7e22ce" },
      { id: "Na2SO4", label: "Na₂SO₄", name: "Sodium Sulfate",   color: "#f97316", dark: "#c2410c" },
      { id: "NaCl",   label: "NaCl",   name: "Sodium Chloride",  color: "#f97316", dark: "#c2410c" },
      { id: "K2CO3",  label: "K₂CO₃",  name: "Potassium Carbonate", color: "#ec4899", dark: "#be185d" },
      { id: "CaCl2",  label: "CaCl₂",  name: "Calcium Chloride", color: "#eab308", dark: "#a16207" },
    ],
    explanation: {
      summary: "Barium Sulfate Precipitation — Double Displacement Reaction",
      mechanism: [
        "BaCl₂ and Na₂SO₄ are both soluble ionic compounds that dissociate completely in water.",
        "In solution: Ba²⁺, Cl⁻, Na⁺, and SO₄²⁻ ions are all present.",
        "Ba²⁺ and SO₄²⁻ ions are strongly attracted — BaSO₄ is extremely insoluble in water (Ksp ≈ 1×10⁻¹⁰).",
        "The ions come together and precipitate as a dense white solid.",
        "Na⁺ and Cl⁻ remain as spectator ions in solution.",
        "Net ionic equation: Ba²⁺(aq) + SO₄²⁻(aq) → BaSO₄(s)↓",
        "Balanced equation: BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl",
      ],
      realWorld: "BaSO₄ is used as a contrast agent in X-ray imaging of the digestive tract (barium meal/swallow).",
      energyType: "Exothermic (slight)",
    },
  },
  {
    id: "double-4",
    type: "double_displacement",
    question: "Lead(II) nitrate solution reacts with potassium iodide solution to form a bright yellow precipitate. Select both reactants.",
    hint: "A toxic soluble lead salt meets an iodide — the result is a vivid yellow solid known as 'golden rain' in chemistry demos.",
    equation: { reactants: ["Pb(NO₃)₂", "KI"], arrow: "→", products: ["PbI₂↓", "KNO₃"], balanced: "Pb(NO₃)₂ + 2KI → PbI₂↓ + 2KNO₃" },
    correctReactants: ["PbNO32", "KI"],
    inventory: [
      { id: "PbNO32", label: "Pb(NO₃)₂", name: "Lead(II) Nitrate", color: "#78716c", dark: "#44403c" },
      { id: "KI",     label: "KI",       name: "Potassium Iodide", color: "#ec4899", dark: "#be185d" },
      { id: "NaCl",   label: "NaCl",     name: "Sodium Chloride",  color: "#f97316", dark: "#c2410c" },
      { id: "AgNO3",  label: "AgNO₃",    name: "Silver Nitrate",   color: "#94a3b8", dark: "#475569" },
      { id: "NaOH",   label: "NaOH",     name: "Sodium Hydroxide", color: "#f97316", dark: "#c2410c" },
    ],
    explanation: {
      summary: "Lead(II) Iodide Precipitation — Double Displacement Reaction",
      mechanism: [
        "Pb(NO₃)₂ and KI are both soluble salts that dissociate completely in water.",
        "In solution: Pb²⁺, NO₃⁻, K⁺, and I⁻ ions are all present.",
        "Pb²⁺ and I⁻ ions combine to form PbI₂, which is insoluble in cold water.",
        "The bright yellow precipitate is lead(II) iodide, famous for the 'golden rain' demonstration.",
        "When heated, PbI₂ dissolves; upon cooling, golden crystals form — a beautiful reversible process.",
        "K⁺ and NO₃⁻ remain as spectator ions in solution.",
        "Net ionic equation: Pb²⁺(aq) + 2I⁻(aq) → PbI₂(s)↓",
        "Balanced equation: Pb(NO₃)₂ + 2KI → PbI₂↓ + 2KNO₃",
      ],
      realWorld: "PbI₂ is used in solar cells (perovskite solar cells) and as a pigment; the 'golden rain' demo is a classic chemistry show.",
      energyType: "Exothermic (slight)",
    },
  },
  {
    id: "double-5",
    type: "double_displacement",
    question: "Sulfuric acid reacts with barium hydroxide to form a white precipitate and water. Select both reactants.",
    hint: "A strong diprotic acid meets a strong base containing a heavy metal — both neutralisation and precipitation occur.",
    equation: { reactants: ["H₂SO₄", "Ba(OH)₂"], arrow: "→", products: ["BaSO₄↓", "H₂O"], balanced: "H₂SO₄ + Ba(OH)₂ → BaSO₄↓ + 2H₂O" },
    correctReactants: ["H2SO4", "BaOH2"],
    inventory: [
      { id: "H2SO4",  label: "H₂SO₄",  name: "Sulfuric Acid",    color: "#dc2626", dark: "#991b1b" },
      { id: "BaOH2",  label: "Ba(OH)₂", name: "Barium Hydroxide", color: "#a855f7", dark: "#7e22ce" },
      { id: "HCl",    label: "HCl",    name: "Hydrochloric Acid", color: "#65a30d", dark: "#3f6212" },
      { id: "NaOH",   label: "NaOH",   name: "Sodium Hydroxide", color: "#f97316", dark: "#c2410c" },
      { id: "CaOH2",  label: "Ca(OH)₂", name: "Calcium Hydroxide", color: "#eab308", dark: "#a16207" },
    ],
    explanation: {
      summary: "Sulfuric Acid + Barium Hydroxide — Double Displacement with Neutralisation",
      mechanism: [
        "H₂SO₄ is a strong diprotic acid: H₂SO₄ → 2H⁺ + SO₄²⁻.",
        "Ba(OH)₂ is a strong base: Ba(OH)₂ → Ba²⁺ + 2OH⁻.",
        "Two processes occur simultaneously: neutralisation (H⁺ + OH⁻ → H₂O) and precipitation (Ba²⁺ + SO₄²⁻ → BaSO₄↓).",
        "The white precipitate of BaSO₄ forms immediately, making this a dramatic demonstration.",
        "The solution goes from acidic to neutral; conductivity drops as ions are removed from solution.",
        "This is both a neutralisation and a precipitation reaction — a 'double' double displacement!",
        "Balanced equation: H₂SO₄ + Ba(OH)₂ → BaSO₄↓ + 2H₂O",
      ],
      realWorld: "Used in analytical chemistry to test for sulfate ions; BaSO₄ is the standard X-ray contrast agent.",
      energyType: "Exothermic",
    },
  },

  // ── ADDITIONAL COMBUSTION ────────────────────────────────────────────────
  {
    id: "combust-3",
    type: "combustion",
    question: "Ethanol (alcohol) burns in oxygen to produce carbon dioxide and water, releasing heat. Select the two reactants.",
    hint: "The alcohol in alcoholic drinks and biofuel meets the gas that supports burning.",
    equation: { reactants: ["C₂H₅OH", "O₂"], arrow: "→", products: ["CO₂", "H₂O"], balanced: "C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O" },
    correctReactants: ["C2H5OH", "O2"],
    inventory: [
      { id: "C2H5OH", label: "C₂H₅OH", name: "Ethanol",        color: "#8b5cf6", dark: "#6d28d9" },
      { id: "O2",     label: "O₂",     name: "Oxygen Gas",     color: "#ef4444", dark: "#b91c1c" },
      { id: "CH4",    label: "CH₄",    name: "Methane",        color: "#0891b2", dark: "#0e7490" },
      { id: "CO2",    label: "CO₂",    name: "Carbon Dioxide", color: "#6b7280", dark: "#374151" },
      { id: "H2O",    label: "H₂O",    name: "Water",          color: "#0ea5e9", dark: "#0369a1" },
    ],
    explanation: {
      summary: "Combustion of Ethanol — Combustion Reaction",
      mechanism: [
        "Ethanol (C₂H₅OH) is an alcohol with two carbon atoms, five hydrogens, and one hydroxyl group.",
        "When ignited, the C–C and C–H bonds break, and the C–O and O–H bonds in the hydroxyl group also break.",
        "Each carbon atom is fully oxidised to CO₂: C + O₂ → CO₂.",
        "Hydrogen atoms combine with oxygen to form water: 2H + ½O₂ → H₂O.",
        "The hydroxyl oxygen becomes part of the products (CO₂ and H₂O).",
        "The reaction releases ~1367 kJ/mol — ethanol is used as a biofuel additive in gasoline (gasohol).",
        "Balanced equation: C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O",
      ],
      realWorld: "Ethanol is blended with gasoline (E10, E85) as a renewable fuel; also used in spirit burners and flambé cooking.",
      energyType: "Exothermic",
    },
  },
  {
    id: "combust-4",
    type: "combustion",
    question: "Glucose (sugar) burns in oxygen to produce carbon dioxide and water — the same reaction that occurs during cellular respiration. Select the two reactants.",
    hint: "The simple sugar that fuels your body meets the gas you breathe in — this is the chemistry of life and fire.",
    equation: { reactants: ["C₆H₁₂O₆", "O₂"], arrow: "→", products: ["CO₂", "H₂O"], balanced: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O" },
    correctReactants: ["C6H12O6", "O2"],
    inventory: [
      { id: "C6H12O6", label: "C₆H₁₂O₆", name: "Glucose",        color: "#f59e0b", dark: "#b45309" },
      { id: "O2",      label: "O₂",      name: "Oxygen Gas",     color: "#ef4444", dark: "#b91c1c" },
      { id: "CH4",     label: "CH₄",     name: "Methane",        color: "#0891b2", dark: "#0e7490" },
      { id: "CO2",     label: "CO₂",     name: "Carbon Dioxide", color: "#6b7280", dark: "#374151" },
      { id: "H2O",     label: "H₂O",     name: "Water",          color: "#0ea5e9", dark: "#0369a1" },
    ],
    explanation: {
      summary: "Combustion of Glucose — Combustion Reaction",
      mechanism: [
        "Glucose (C₆H₁₂O₆) is a 6-carbon sugar — the primary energy source for most living organisms.",
        "In combustion, the molecule is completely oxidised: all 6 carbons become CO₂ and all 12 hydrogens become H₂O.",
        "The reaction requires 6 O₂ molecules — one for each carbon and additional oxygen for the hydrogens.",
        "This is the same overall reaction as aerobic cellular respiration, but combustion is rapid and uncontrolled.",
        "In cells, the same reaction occurs in many small, enzyme-controlled steps, releasing energy gradually as ATP.",
        "The total energy released is ~2803 kJ/mol — enough to sustain life processes.",
        "Balanced equation: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O",
      ],
      realWorld: "This reaction powers life itself through cellular respiration; burning sugar is used in fire-eating performances and rocket candy.",
      energyType: "Exothermic",
    },
  },
];


export default REACTIONS