// ─── Cell Sandbox constants ───────────────────────────────────────────────────

export const CELL_MODES = {
  BUILDER:    "builder",
  MICROSCOPE: "microscope",
  DIVISION:   "division",
};

export const CELL_TYPES = {
  ANIMAL:    "animal",
  PLANT:     "plant",
  BACTERIAL: "bacterial",
};

export const DIVISION_TYPES = {
  MITOSIS:  "mitosis",
  MEIOSIS:  "meiosis",
  ASEXUAL:  "asexual",
};

export const ASEXUAL_TYPES = {
  FISSION:       "fission",
  BUDDING:       "budding",
  REGENERATION:  "regeneration",
};

// ─── Organelle definitions ────────────────────────────────────────────────────
// Each organelle: id, label, emoji, color, found in (cell types), description
export const ORGANELLES = [
  {
    id:          "nucleus",
    label:       "Nucleus",
    emoji:       "⭕",
    color:       "#58a6ff",
    glow:        "rgba(88,166,255,0.35)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: false,  // prokaryotes have no membrane-bound nucleus
    description: "Control centre of the cell. Contains DNA and directs all cellular activities.",
    fact:        "Discovered by Robert Brown in 1831.",
    required:    true,
  },
  {
    id:          "mitochondria",
    label:       "Mitochondria",
    emoji:       "🔋",
    color:       "#f47067",
    glow:        "rgba(244,112,103,0.35)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: false,
    description: "Powerhouse of the cell. Produces ATP through cellular respiration.",
    fact:        "Has its own DNA, suggesting it was once a free-living bacterium.",
    required:    true,
  },
  {
    id:          "cell_membrane",
    label:       "Plasma Membrane",
    emoji:       "🛡️",
    color:       "#39d353",
    glow:        "rgba(57,211,83,0.35)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: true,
    description: "Selectively permeable boundary that controls what enters and exits the cell.",
    fact:        "Made of a phospholipid bilayer — two layers of fat molecules.",
    required:    true,
  },
  {
    id:          "cell_wall",
    label:       "Cell Wall",
    emoji:       "🧱",
    color:       "#e3b341",
    glow:        "rgba(227,179,65,0.35)",
    inAnimal:    false,
    inPlant:     true,
    inBacterial: true,
    description: "Rigid outer layer made of cellulose (plants) or peptidoglycan (bacteria). Provides structural support.",
    fact:        "Plant cell walls give wood its strength.",
    required:    false,
  },
  {
    id:          "chloroplast",
    label:       "Chloroplast",
    emoji:       "🍃",
    color:       "#1abc9c",
    glow:        "rgba(26,188,156,0.35)",
    inAnimal:    false,
    inPlant:     true,
    inBacterial: false,
    description: "Site of photosynthesis. Converts light energy into chemical energy (glucose).",
    fact:        "Contains the green pigment chlorophyll.",
    required:    false,
  },
  {
    id:          "vacuole",
    label:       "Vacuole",
    emoji:       "💧",
    color:       "#00e5ff",
    glow:        "rgba(0,229,255,0.35)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: false,
    description: "Storage organelle. Plant cells have a large central vacuole for water/turgor pressure; animal cells have smaller ones.",
    fact:        "A plant's central vacuole can take up 90% of cell volume.",
    required:    false,
  },
  {
    id:          "ribosome",
    label:       "Ribosome",
    emoji:       "🔵",
    color:       "#bd93f9",
    glow:        "rgba(189,147,249,0.35)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: true,
    description: "Site of protein synthesis. Reads mRNA instructions to build proteins.",
    fact:        "So small that 10 million ribosomes could fit on the head of a pin.",
    required:    false,
  },
  {
    id:          "golgi",
    label:       "Golgi Body",
    emoji:       "📦",
    color:       "#ff79c6",
    glow:        "rgba(255,121,198,0.35)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: false,
    description: "Cell's post office. Packages and dispatches proteins and lipids to their destinations.",
    fact:        "Named after Italian scientist Camillo Golgi, who discovered it in 1897.",
    required:    false,
  },
  {
    id:          "er_rough",
    label:       "Rough ER",
    emoji:       "🌊",
    color:       "#f8f8f2",
    glow:        "rgba(248,248,242,0.2)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: false,
    description: "Studded with ribosomes. Manufactures and transports proteins.",
    fact:        "The 'rough' refers to the ribosomes attached on its surface.",
    required:    false,
  },
  {
    id:          "lysosome",
    label:       "Lysosome",
    emoji:       "🧹",
    color:       "#ff6b6b",
    glow:        "rgba(255,107,107,0.35)",
    inAnimal:    true,
    inPlant:     false,
    inBacterial: false,
    description: "Digestive organelle. Contains enzymes to break down waste, debris, and foreign material.",
    fact:        "Called the 'suicide bag' because it can self-destruct a damaged cell.",
    required:    false,
  },
  {
    id:          "cytoplasm",
    label:       "Cytoplasm",
    emoji:       "🌫️",
    color:       "#6ee7f7",
    glow:        "rgba(110,231,247,0.25)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: true,
    description: "Gel-like fluid (cytosol) filling the cell, suspending all organelles and enabling chemical reactions.",
    fact:        "About 70% water — it acts as the cell's internal transport medium.",
    required:    true,
  },
  {
    id:          "er_smooth",
    label:       "Smooth ER",
    emoji:       "〰️",
    color:       "#a78bfa",
    glow:        "rgba(167,139,250,0.35)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: false,
    description: "Synthesises lipids, phospholipids and steroids. Also detoxifies drugs and stores calcium ions.",
    fact:        "Lacks ribosomes — hence 'smooth' compared to the granular Rough ER.",
    required:    false,
  },
  {
    id:          "peroxisome",
    label:       "Peroxisome",
    emoji:       "⚗️",
    color:       "#fbbf24",
    glow:        "rgba(251,191,36,0.35)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: false,
    description: "Breaks down fatty acids and neutralises hydrogen peroxide (H₂O₂) using catalase enzymes.",
    fact:        "Generates and immediately destroys H₂O₂, protecting the cell from oxidative damage.",
    required:    false,
  },
  {
    id:          "centriole",
    label:       "Centriole",
    emoji:       "🟡",
    color:       "#e3b341",
    glow:        "rgba(227,179,65,0.35)",
    inAnimal:    true,
    inPlant:     false,
    inBacterial: false,
    description: "Cylindrical organelles helper that organises spindle fibres for cell division.",
    fact:        "Centrioles occur in pairs, aligned perpendicularly near the nucleus.",
    required:    false,
  },
  {
    id:          "microtubule",
    label:       "Microtubule",
    emoji:       "🥢",
    color:       "#d4b26f",
    glow:        "rgba(212,178,111,0.25)",
    inAnimal:    true,
    inPlant:     true,
    inBacterial: false,
    description: "Hollow tubulin protein cylinders that provide structural support and act as cellular highways.",
    fact:        "They grow outward from the centrosome to form a radiating cytoskeletal network.",
    required:    false,
  },
  {
    id:          "flagella",
    label:       "Flagella",
    emoji:       "🌀",
    color:       "#50fa7b",
    glow:        "rgba(80,250,123,0.3)",
    inAnimal:    false,
    inPlant:     false,
    inBacterial: true,
    description: "Whip-like tail that propels bacteria through liquid environments.",
    fact:        "A bacterial flagellum rotates like a motor at up to 100,000 RPM.",
    required:    false,
  },
  {
    id:          "nucleoid",
    label:       "Nucleoid",
    emoji:       "🧶",
    color:       "#ffb86c",
    glow:        "rgba(255,184,108,0.35)",
    inAnimal:    false,
    inPlant:     false,
    inBacterial: true,
    description: "Region in prokaryotes where the circular DNA is concentrated (not membrane-bound).",
    fact:        "Unlike a eukaryotic nucleus, the nucleoid has no surrounding membrane.",
    required:    false,
  },
];

// Mitosis phases with descriptions
export const MITOSIS_PHASES = [
  {
    id:          "interphase",
    label:       "Interphase",
    color:       "#58a6ff",
    description: "Cell grows and DNA is replicated. Chromosomes are not yet visible.",
    detail:      "The cell spends ~90% of its life in interphase, preparing for division.",
  },
  {
    id:          "prophase",
    label:       "Prophase",
    color:       "#bd93f9",
    description: "Chromosomes condense and become visible. Spindle fibres begin to form.",
    detail:      "The nuclear envelope breaks down at the end of prophase.",
  },
  {
    id:          "metaphase",
    label:       "Metaphase",
    color:       "#ff79c6",
    description: "Chromosomes align at the cell's equatorial plate (metaphase plate).",
    detail:      "Spindle fibres attach to the centromeres of each chromosome.",
  },
  {
    id:          "anaphase",
    label:       "Anaphase",
    color:       "#f47067",
    description: "Sister chromatids are pulled to opposite poles of the cell.",
    detail:      "The cell elongates as chromatids move apart.",
  },
  {
    id:          "telophase",
    label:       "Telophase",
    color:       "#e3b341",
    description: "Nuclear envelopes reform around each set of chromosomes. Chromosomes de-condense.",
    detail:      "Two distinct nuclei are now visible inside the cell.",
  },
  {
    id:          "cytokinesis",
    label:       "Cytokinesis",
    color:       "#39d353",
    description: "Cytoplasm divides, completing the formation of 2 daughter cells (identical to parent).",
    detail:      "Result: 2 diploid daughter cells, genetically identical to the original.",
  },
];

// Meiosis phases (simplified — 2 divisions)
export const MEIOSIS_PHASES = [
  {
    id:          "prophase1",
    label:       "Prophase I",
    color:       "#58a6ff",
    description: "Homologous chromosomes pair up (synapsis). Crossing-over occurs between non-sister chromatids.",
    detail:      "Crossing-over shuffles genetic material — a key source of variation.",
  },
  {
    id:          "metaphase1",
    label:       "Metaphase I",
    color:       "#bd93f9",
    description: "Homologous chromosome pairs align at the metaphase plate.",
    detail:      "Independent assortment here is another source of genetic diversity.",
  },
  {
    id:          "anaphase1",
    label:       "Anaphase I",
    color:       "#ff79c6",
    description: "Homologous chromosomes (not chromatids) are pulled to opposite poles.",
    detail:      "Chromosome number halved: this is the reductional division.",
  },
  {
    id:          "telophase1",
    label:       "Telophase I",
    color:       "#f47067",
    description: "Two cells formed, each with half the original chromosome number (haploid).",
    detail:      "Each chromosome still consists of 2 sister chromatids joined at centromere.",
  },
  {
    id:          "meiosis2",
    label:       "Meiosis II",
    color:       "#e3b341",
    description: "Second division: similar to mitosis. Sister chromatids are separated.",
    detail:      "No DNA replication occurs between Meiosis I and II.",
  },
  {
    id:          "gametes",
    label:       "Gametes",
    color:       "#39d353",
    description: "Result: 4 haploid daughter cells (gametes), each genetically unique.",
    detail:      "Meiosis is the basis of sexual reproduction and genetic variation.",
  },
];
