const AtomData = [
  {
    "element": "Hydrogen",
    "symbol": "H",
    "atomic_number": 1,
    "atomic_mass": 1.008,
    "category": "Nonmetals",
    "group": 1,
    "valency": 1,
    "common_charge": "+1/-1",
    "bonding_type": "Covalent",
    "electronegativity": 2.20,
    "electron_configuration": "1s¹",
    "state": "Gas",
    "hex_code": "#3b82f6"
  },
  {
    "element": "Helium",
    "symbol": "He",
    "atomic_number": 2,
    "atomic_mass": 4.0026,
    "category": "Noble Gases",
    "group": 18,
    "valency": 0,
    "common_charge": "0",
    "bonding_type": "Atomic",
    "electronegativity": 0.0,
    "electron_configuration": "1s²",
    "state": "Gas",
    "hex_code": "#ec4899"
  },
  {
    "element": "Lithium",
    "symbol": "Li",
    "atomic_number": 3,
    "atomic_mass": 6.94,
    "category": "Alkali Metals",
    "group": 1,
    "valency": 1,
    "common_charge": "+1",
    "bonding_type": "Metallic",
    "electronegativity": 0.98,
    "electron_configuration": "1s² 2s¹",
    "state": "Solid",
    "hex_code": "#ef4444"
  },
  {
    "element": "Beryllium",
    "symbol": "Be",
    "atomic_number": 4,
    "atomic_mass": 9.0122,
    "category": "Alkaline Earth",
    "group": 2,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.57,
    "electron_configuration": "1s² 2s²",
    "state": "Solid",
    "hex_code": "#f97316"
  },
  {
    "element": "Boron",
    "symbol": "B",
    "atomic_number": 5,
    "atomic_mass": 10.81,
    "category": "Metalloids",
    "group": 13,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Covalent",
    "electronegativity": 2.04,
    "electron_configuration": "1s² 2s² 2p¹",
    "state": "Solid",
    "hex_code": "#14b8a6"
  },
  {
    "element": "Carbon",
    "symbol": "C",
    "atomic_number": 6,
    "atomic_mass": 12.011,
    "category": "Nonmetals",
    "group": 14,
    "valency": 4,
    "common_charge": "+4/-4",
    "bonding_type": "Covalent",
    "electronegativity": 2.55,
    "electron_configuration": "1s² 2s² 2p²",
    "state": "Solid",
    "hex_code": "#3b82f6"
  },
  {
    "element": "Nitrogen",
    "symbol": "N",
    "atomic_number": 7,
    "atomic_mass": 14.007,
    "category": "Nonmetals",
    "group": 15,
    "valency": 3,
    "common_charge": "-3",
    "bonding_type": "Covalent",
    "electronegativity": 3.04,
    "electron_configuration": "1s² 2s² 2p³",
    "state": "Gas",
    "hex_code": "#3b82f6"
  },
  {
    "element": "Oxygen",
    "symbol": "O",
    "atomic_number": 8,
    "atomic_mass": 15.999,
    "category": "Nonmetals",
    "group": 16,
    "valency": 2,
    "common_charge": "-2",
    "bonding_type": "Covalent",
    "electronegativity": 3.44,
    "electron_configuration": "1s² 2s² 2p⁴",
    "state": "Gas",
    "hex_code": "#3b82f6"
  },
  {
    "element": "Fluorine",
    "symbol": "F",
    "atomic_number": 9,
    "atomic_mass": 18.998,
    "category": "Halogens",
    "group": 17,
    "valency": 1,
    "common_charge": "-1",
    "bonding_type": "Covalent",
    "electronegativity": 3.98,
    "electron_configuration": "1s² 2s² 2p⁵",
    "state": "Gas",
    "hex_code": "#a855f7"
  },
  {
    "element": "Neon",
    "symbol": "Ne",
    "atomic_number": 10,
    "atomic_mass": 20.180,
    "category": "Noble Gases",
    "group": 18,
    "valency": 0,
    "common_charge": "0",
    "bonding_type": "Atomic",
    "electronegativity": 0.0,
    "electron_configuration": "1s² 2s² 2p⁶",
    "state": "Gas",
    "hex_code": "#ec4899"
  },
  {
    "element": "Sodium",
    "symbol": "Na",
    "atomic_number": 11,
    "atomic_mass": 22.990,
    "category": "Alkali Metals",
    "group": 1,
    "valency": 1,
    "common_charge": "+1",
    "bonding_type": "Metallic",
    "electronegativity": 0.93,
    "electron_configuration": "1s² 2s² 2p⁶ 3s¹",
    "state": "Solid",
    "hex_code": "#ef4444"
  },
  {
    "element": "Magnesium",
    "symbol": "Mg",
    "atomic_number": 12,
    "atomic_mass": 24.305,
    "category": "Alkaline Earth",
    "group": 2,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.31,
    "electron_configuration": "[Ne] 3s²",
    "state": "Solid",
    "hex_code": "#f97316"
  },
  {
    "element": "Aluminum",
    "symbol": "Al",
    "atomic_number": 13,
    "atomic_mass": 26.982,
    "category": "Post-Transition",
    "group": 13,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.61,
    "electron_configuration": "[Ne] 3s² 3p¹",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Silicon",
    "symbol": "Si",
    "atomic_number": 14,
    "atomic_mass": 28.085,
    "category": "Metalloids",
    "group": 14,
    "valency": 4,
    "common_charge": "+4/-4",
    "bonding_type": "Covalent",
    "electronegativity": 1.90,
    "electron_configuration": "[Ne] 3s² 3p²",
    "state": "Solid",
    "hex_code": "#14b8a6"
  },
  {
    "element": "Phosphorus",
    "symbol": "P",
    "atomic_number": 15,
    "atomic_mass": 30.974,
    "category": "Nonmetals",
    "group": 15,
    "valency": 3,
    "common_charge": "-3",
    "bonding_type": "Covalent",
    "electronegativity": 2.19,
    "electron_configuration": "[Ne] 3s² 3p³",
    "state": "Solid",
    "hex_code": "#3b82f6"
  },
  {
    "element": "Sulfur",
    "symbol": "S",
    "atomic_number": 16,
    "atomic_mass": 32.06,
    "category": "Nonmetals",
    "group": 16,
    "valency": 2,
    "common_charge": "-2",
    "bonding_type": "Covalent",
    "electronegativity": 2.58,
    "electron_configuration": "[Ne] 3s² 3p⁴",
    "state": "Solid",
    "hex_code": "#3b82f6"
  },
  {
    "element": "Chlorine",
    "symbol": "Cl",
    "atomic_number": 17,
    "atomic_mass": 35.45,
    "category": "Halogens",
    "group": 17,
    "valency": 1,
    "common_charge": "-1",
    "bonding_type": "Covalent",
    "electronegativity": 3.16,
    "electron_configuration": "[Ne] 3s² 3p⁵",
    "state": "Gas",
    "hex_code": "#a855f7"
  },
  {
    "element": "Argon",
    "symbol": "Ar",
    "atomic_number": 18,
    "atomic_mass": 39.948,
    "category": "Noble Gases",
    "group": 18,
    "valency": 0,
    "common_charge": "0",
    "bonding_type": "Atomic",
    "electronegativity": 0.0,
    "electron_configuration": "[Ne] 3s² 3p⁶",
    "state": "Gas",
    "hex_code": "#ec4899"
  },
  {
    "element": "Potassium",
    "symbol": "K",
    "atomic_number": 19,
    "atomic_mass": 39.098,
    "category": "Alkali Metals",
    "group": 1,
    "valency": 1,
    "common_charge": "+1",
    "bonding_type": "Metallic",
    "electronegativity": 0.82,
    "electron_configuration": "[Ar] 4s¹",
    "state": "Solid",
    "hex_code": "#ef4444"
  },
  {
    "element": "Calcium",
    "symbol": "Ca",
    "atomic_number": 20,
    "atomic_mass": 40.078,
    "category": "Alkaline Earth",
    "group": 2,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.00,
    "electron_configuration": "[Ar] 4s²",
    "state": "Solid",
    "hex_code": "#f97316"
  },
  {
    "element": "Scandium",
    "symbol": "Sc",
    "atomic_number": 21,
    "atomic_mass": 44.956,
    "category": "Transition Metals",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.36,
    "electron_configuration": "[Ar] 3d¹ 4s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Titanium",
    "symbol": "Ti",
    "atomic_number": 22,
    "atomic_mass": 47.867,
    "category": "Transition Metals",
    "group": 4,
    "valency": 4,
    "common_charge": "+4",
    "bonding_type": "Metallic",
    "electronegativity": 1.54,
    "electron_configuration": "[Ar] 3d² 4s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Vanadium",
    "symbol": "V",
    "atomic_number": 23,
    "atomic_mass": 50.942,
    "category": "Transition Metals",
    "group": 5,
    "valency": 5,
    "common_charge": "+5",
    "bonding_type": "Metallic",
    "electronegativity": 1.63,
    "electron_configuration": "[Ar] 3d³ 4s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Chromium",
    "symbol": "Cr",
    "atomic_number": 24,
    "atomic_mass": 51.996,
    "category": "Transition Metals",
    "group": 6,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.66,
    "electron_configuration": "[Ar] 3d⁵ 4s¹",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Manganese",
    "symbol": "Mn",
    "atomic_number": 25,
    "atomic_mass": 54.938,
    "category": "Transition Metals",
    "group": 7,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.55,
    "electron_configuration": "[Ar] 3d⁵ 4s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Iron",
    "symbol": "Fe",
    "atomic_number": 26,
    "atomic_mass": 55.845,
    "category": "Transition Metals",
    "group": 8,
    "valency": 3,
    "common_charge": "+3/+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.83,
    "electron_configuration": "[Ar] 3d⁶ 4s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Cobalt",
    "symbol": "Co",
    "atomic_number": 27,
    "atomic_mass": 58.933,
    "category": "Transition Metals",
    "group": 9,
    "valency": 3,
    "common_charge": "+3/+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.88,
    "electron_configuration": "[Ar] 3d⁷ 4s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Nickel",
    "symbol": "Ni",
    "atomic_number": 28,
    "atomic_mass": 58.693,
    "category": "Transition Metals",
    "group": 10,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.91,
    "electron_configuration": "[Ar] 3d⁸ 4s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Copper",
    "symbol": "Cu",
    "atomic_number": 29,
    "atomic_mass": 63.546,
    "category": "Transition Metals",
    "group": 11,
    "valency": 2,
    "common_charge": "+2/+1",
    "bonding_type": "Metallic",
    "electronegativity": 1.90,
    "electron_configuration": "[Ar] 3d¹⁰ 4s¹",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Zinc",
    "symbol": "Zn",
    "atomic_number": 30,
    "atomic_mass": 65.38,
    "category": "Transition Metals",
    "group": 12,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.65,
    "electron_configuration": "[Ar] 3d¹⁰ 4s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Gallium",
    "symbol": "Ga",
    "atomic_number": 31,
    "atomic_mass": 69.723,
    "category": "Post-Transition",
    "group": 13,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.81,
    "electron_configuration": "[Ar] 3d¹⁰ 4s² 4p¹",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Germanium",
    "symbol": "Ge",
    "atomic_number": 32,
    "atomic_mass": 72.630,
    "category": "Metalloids",
    "group": 14,
    "valency": 4,
    "common_charge": "+4",
    "bonding_type": "Covalent",
    "electronegativity": 2.01,
    "electron_configuration": "[Ar] 3d¹⁰ 4s² 4p²",
    "state": "Solid",
    "hex_code": "#14b8a6"
  },
  {
    "element": "Arsenic",
    "symbol": "As",
    "atomic_number": 33,
    "atomic_mass": 74.922,
    "category": "Metalloids",
    "group": 15,
    "valency": 3,
    "common_charge": "-3",
    "bonding_type": "Covalent",
    "electronegativity": 2.18,
    "electron_configuration": "[Ar] 3d¹⁰ 4s² 4p³",
    "state": "Solid",
    "hex_code": "#14b8a6"
  },
  {
    "element": "Selenium",
    "symbol": "Se",
    "atomic_number": 34,
    "atomic_mass": 78.971,
    "category": "Nonmetals",
    "group": 16,
    "valency": 2,
    "common_charge": "-2",
    "bonding_type": "Covalent",
    "electronegativity": 2.55,
    "electron_configuration": "[Ar] 3d¹⁰ 4s² 4p⁴",
    "state": "Solid",
    "hex_code": "#3b82f6"
  },
  {
    "element": "Bromine",
    "symbol": "Br",
    "atomic_number": 35,
    "atomic_mass": 79.904,
    "category": "Halogens",
    "group": 17,
    "valency": 1,
    "common_charge": "-1",
    "bonding_type": "Covalent",
    "electronegativity": 2.96,
    "electron_configuration": "[Ar] 3d¹⁰ 4s² 4p⁵",
    "state": "Liquid",
    "hex_code": "#a855f7"
  },
  {
    "element": "Krypton",
    "symbol": "Kr",
    "atomic_number": 36,
    "atomic_mass": 83.798,
    "category": "Noble Gases",
    "group": 18,
    "valency": 0,
    "common_charge": "0",
    "bonding_type": "Atomic",
    "electronegativity": 3.00,
    "electron_configuration": "[Ar] 3d¹⁰ 4s² 4p⁶",
    "state": "Gas",
    "hex_code": "#ec4899"
  },
  {
    "element": "Rubidium",
    "symbol": "Rb",
    "atomic_number": 37,
    "atomic_mass": 85.468,
    "category": "Alkali Metals",
    "group": 1,
    "valency": 1,
    "common_charge": "+1",
    "bonding_type": "Metallic",
    "electronegativity": 0.82,
    "electron_configuration": "[Kr] 5s¹",
    "state": "Solid",
    "hex_code": "#ef4444"
  },
  {
    "element": "Strontium",
    "symbol": "Sr",
    "atomic_number": 38,
    "atomic_mass": 87.62,
    "category": "Alkaline Earth",
    "group": 2,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 0.95,
    "electron_configuration": "[Kr] 5s²",
    "state": "Solid",
    "hex_code": "#f97316"
  },
  {
    "element": "Yttrium",
    "symbol": "Y",
    "atomic_number": 39,
    "atomic_mass": 88.906,
    "category": "Transition Metals",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.22,
    "electron_configuration": "[Kr] 4d¹ 5s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Zirconium",
    "symbol": "Zr",
    "atomic_number": 40,
    "atomic_mass": 91.224,
    "category": "Transition Metals",
    "group": 4,
    "valency": 4,
    "common_charge": "+4",
    "bonding_type": "Metallic",
    "electronegativity": 1.33,
    "electron_configuration": "[Kr] 4d² 5s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Niobium",
    "symbol": "Nb",
    "atomic_number": 41,
    "atomic_mass": 92.906,
    "category": "Transition Metals",
    "group": 5,
    "valency": 5,
    "common_charge": "+5",
    "bonding_type": "Metallic",
    "electronegativity": 1.60,
    "electron_configuration": "[Kr] 4d⁴ 5s¹",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Molybdenum",
    "symbol": "Mo",
    "atomic_number": 42,
    "atomic_mass": 95.95,
    "category": "Transition Metals",
    "group": 6,
    "valency": 6,
    "common_charge": "+6",
    "bonding_type": "Metallic",
    "electronegativity": 2.16,
    "electron_configuration": "[Kr] 4d⁵ 5s¹",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Technetium",
    "symbol": "Tc",
    "atomic_number": 43,
    "atomic_mass": 98.0,
    "category": "Transition Metals",
    "group": 7,
    "valency": 7,
    "common_charge": "+7",
    "bonding_type": "Metallic",
    "electronegativity": 1.90,
    "electron_configuration": "[Kr] 4d⁵ 5s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Ruthenium",
    "symbol": "Ru",
    "atomic_number": 44,
    "atomic_mass": 101.07,
    "category": "Transition Metals",
    "group": 8,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 2.20,
    "electron_configuration": "[Kr] 4d⁷ 5s¹",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Rhodium",
    "symbol": "Rh",
    "atomic_number": 45,
    "atomic_mass": 102.91,
    "category": "Transition Metals",
    "group": 9,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 2.28,
    "electron_configuration": "[Kr] 4d⁸ 5s¹",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Palladium",
    "symbol": "Pd",
    "atomic_number": 46,
    "atomic_mass": 106.42,
    "category": "Transition Metals",
    "group": 10,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 2.20,
    "electron_configuration": "[Kr] 4d¹⁰",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Silver",
    "symbol": "Ag",
    "atomic_number": 47,
    "atomic_mass": 107.87,
    "category": "Transition Metals",
    "group": 11,
    "valency": 1,
    "common_charge": "+1",
    "bonding_type": "Metallic",
    "electronegativity": 1.93,
    "electron_configuration": "[Kr] 4d¹⁰ 5s¹",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Cadmium",
    "symbol": "Cd",
    "atomic_number": 48,
    "atomic_mass": 112.41,
    "category": "Transition Metals",
    "group": 12,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.69,
    "electron_configuration": "[Kr] 4d¹⁰ 5s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Indium",
    "symbol": "In",
    "atomic_number": 49,
    "atomic_mass": 114.82,
    "category": "Post-Transition",
    "group": 13,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.78,
    "electron_configuration": "[Kr] 4d¹⁰ 5s² 5p¹",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Tin",
    "symbol": "Sn",
    "atomic_number": 50,
    "atomic_mass": 118.71,
    "category": "Post-Transition",
    "group": 14,
    "valency": 4,
    "common_charge": "+4/+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.96,
    "electron_configuration": "[Kr] 4d¹⁰ 5s² 5p²",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Antimony",
    "symbol": "Sb",
    "atomic_number": 51,
    "atomic_mass": 121.76,
    "category": "Metalloids",
    "group": 15,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Covalent",
    "electronegativity": 2.05,
    "electron_configuration": "[Kr] 4d¹⁰ 5s² 5p³",
    "state": "Solid",
    "hex_code": "#14b8a6"
  },
  {
    "element": "Tellurium",
    "symbol": "Te",
    "atomic_number": 52,
    "atomic_mass": 127.60,
    "category": "Metalloids",
    "group": 16,
    "valency": 2,
    "common_charge": "-2",
    "bonding_type": "Covalent",
    "electronegativity": 2.10,
    "electron_configuration": "[Kr] 4d¹⁰ 5s² 5p⁴",
    "state": "Solid",
    "hex_code": "#14b8a6"
  },
  {
    "element": "Iodine",
    "symbol": "I",
    "atomic_number": 53,
    "atomic_mass": 126.90,
    "category": "Halogens",
    "group": 17,
    "valency": 1,
    "common_charge": "-1",
    "bonding_type": "Covalent",
    "electronegativity": 2.66,
    "electron_configuration": "[Kr] 4d¹⁰ 5s² 5p⁵",
    "state": "Solid",
    "hex_code": "#a855f7"
  },
  {
    "element": "Xenon",
    "symbol": "Xe",
    "atomic_number": 54,
    "atomic_mass": 131.29,
    "category": "Noble Gases",
    "group": 18,
    "valency": 0,
    "common_charge": "0",
    "bonding_type": "Atomic",
    "electronegativity": 2.60,
    "electron_configuration": "[Kr] 4d¹⁰ 5s² 5p⁶",
    "state": "Gas",
    "hex_code": "#ec4899"
  },
  {
    "element": "Cesium",
    "symbol": "Cs",
    "atomic_number": 55,
    "atomic_mass": 132.91,
    "category": "Alkali Metals",
    "group": 1,
    "valency": 1,
    "common_charge": "+1",
    "bonding_type": "Metallic",
    "electronegativity": 0.79,
    "electron_configuration": "[Xe] 6s¹",
    "state": "Solid",
    "hex_code": "#ef4444"
  },
  {
    "element": "Barium",
    "symbol": "Ba",
    "atomic_number": 56,
    "atomic_mass": 137.33,
    "category": "Alkaline Earth",
    "group": 2,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 0.89,
    "electron_configuration": "[Xe] 6s²",
    "state": "Solid",
    "hex_code": "#f97316"
  },
  {
    "element": "Lanthanum",
    "symbol": "La",
    "atomic_number": 57,
    "atomic_mass": 138.91,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.10,
    "electron_configuration": "[Xe] 5d¹ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Cerium",
    "symbol": "Ce",
    "atomic_number": 58,
    "atomic_mass": 140.12,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.12,
    "electron_configuration": "[Xe] 4f¹ 5d¹ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Praseodymium",
    "symbol": "Pr",
    "atomic_number": 59,
    "atomic_mass": 140.91,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.13,
    "electron_configuration": "[Xe] 4f³ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Neodymium",
    "symbol": "Nd",
    "atomic_number": 60,
    "atomic_mass": 144.24,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.14,
    "electron_configuration": "[Xe] 4f⁴ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Promethium",
    "symbol": "Pm",
    "atomic_number": 61,
    "atomic_mass": 145.0,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.13,
    "electron_configuration": "[Xe] 4f⁵ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Samarium",
    "symbol": "Sm",
    "atomic_number": 62,
    "atomic_mass": 150.36,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.17,
    "electron_configuration": "[Xe] 4f⁶ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Europium",
    "symbol": "Eu",
    "atomic_number": 63,
    "atomic_mass": 151.96,
    "category": "Lanthanides",
    "group": 3,
    "valency": 2,
    "common_charge": "+2/+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.20,
    "electron_configuration": "[Xe] 4f⁷ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Gadolinium",
    "symbol": "Gd",
    "atomic_number": 64,
    "atomic_mass": 157.25,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.20,
    "electron_configuration": "[Xe] 4f⁷ 5d¹ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Terbium",
    "symbol": "Tb",
    "atomic_number": 65,
    "atomic_mass": 158.93,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.20,
    "electron_configuration": "[Xe] 4f⁹ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Dysprosium",
    "symbol": "Dy",
    "atomic_number": 66,
    "atomic_mass": 162.50,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.22,
    "electron_configuration": "[Xe] 4f¹⁰ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Holmium",
    "symbol": "Ho",
    "atomic_number": 67,
    "atomic_mass": 164.93,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.23,
    "electron_configuration": "[Xe] 4f¹¹ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Erbium",
    "symbol": "Er",
    "atomic_number": 68,
    "atomic_mass": 167.26,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.24,
    "electron_configuration": "[Xe] 4f¹² 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Thulium",
    "symbol": "Tm",
    "atomic_number": 69,
    "atomic_mass": 168.93,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.25,
    "electron_configuration": "[Xe] 4f¹³ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Ytterbium",
    "symbol": "Yb",
    "atomic_number": 70,
    "atomic_mass": 173.05,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.10,
    "electron_configuration": "[Xe] 4f¹⁴ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Lutetium",
    "symbol": "Lu",
    "atomic_number": 71,
    "atomic_mass": 174.97,
    "category": "Lanthanides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.27,
    "electron_configuration": "[Xe] 4f¹⁴ 5d¹ 6s²",
    "state": "Solid",
    "hex_code": "#f472b6"
  },
  {
    "element": "Hafnium",
    "symbol": "Hf",
    "atomic_number": 72,
    "atomic_mass": 178.49,
    "category": "Transition Metals",
    "group": 4,
    "valency": 4,
    "common_charge": "+4",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Xe] 4f¹⁴ 5d² 6s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Tantalum",
    "symbol": "Ta",
    "atomic_number": 73,
    "atomic_mass": 180.95,
    "category": "Transition Metals",
    "group": 5,
    "valency": 5,
    "common_charge": "+5",
    "bonding_type": "Metallic",
    "electronegativity": 1.50,
    "electron_configuration": "[Xe] 4f¹⁴ 5d³ 6s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Tungsten",
    "symbol": "W",
    "atomic_number": 74,
    "atomic_mass": 183.84,
    "category": "Transition Metals",
    "group": 6,
    "valency": 6,
    "common_charge": "+6",
    "bonding_type": "Metallic",
    "electronegativity": 2.36,
    "electron_configuration": "[Xe] 4f¹⁴ 5d⁴ 6s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Rhenium",
    "symbol": "Re",
    "atomic_number": 75,
    "atomic_mass": 186.21,
    "category": "Transition Metals",
    "group": 7,
    "valency": 7,
    "common_charge": "+7",
    "bonding_type": "Metallic",
    "electronegativity": 1.90,
    "electron_configuration": "[Xe] 4f¹⁴ 5d⁵ 6s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Osmium",
    "symbol": "Os",
    "atomic_number": 76,
    "atomic_mass": 190.23,
    "category": "Transition Metals",
    "group": 8,
    "valency": 4,
    "common_charge": "+4",
    "bonding_type": "Metallic",
    "electronegativity": 2.20,
    "electron_configuration": "[Xe] 4f¹⁴ 5d⁶ 6s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Iridium",
    "symbol": "Ir",
    "atomic_number": 77,
    "atomic_mass": 192.22,
    "category": "Transition Metals",
    "group": 9,
    "valency": 4,
    "common_charge": "+4",
    "bonding_type": "Metallic",
    "electronegativity": 2.20,
    "electron_configuration": "[Xe] 4f¹⁴ 5d⁷ 6s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Platinum",
    "symbol": "Pt",
    "atomic_number": 78,
    "atomic_mass": 195.08,
    "category": "Transition Metals",
    "group": 10,
    "valency": 4,
    "common_charge": "+4/+2",
    "bonding_type": "Metallic",
    "electronegativity": 2.28,
    "electron_configuration": "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Gold",
    "symbol": "Au",
    "atomic_number": 79,
    "atomic_mass": 196.97,
    "category": "Transition Metals",
    "group": 11,
    "valency": 3,
    "common_charge": "+3/+1",
    "bonding_type": "Metallic",
    "electronegativity": 2.54,
    "electron_configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Mercury",
    "symbol": "Hg",
    "atomic_number": 80,
    "atomic_mass": 200.59,
    "category": "Transition Metals",
    "group": 12,
    "valency": 2,
    "common_charge": "+2/+1",
    "bonding_type": "Metallic",
    "electronegativity": 2.00,
    "electron_configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    "state": "Liquid",
    "hex_code": "#eab308"
  },
  {
    "element": "Thallium",
    "symbol": "Tl",
    "atomic_number": 81,
    "atomic_mass": 204.38,
    "category": "Post-Transition",
    "group": 13,
    "valency": 3,
    "common_charge": "+1/+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.62,
    "electron_configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Lead",
    "symbol": "Pb",
    "atomic_number": 82,
    "atomic_mass": 207.2,
    "category": "Post-Transition",
    "group": 14,
    "valency": 2,
    "common_charge": "+2/+4",
    "bonding_type": "Metallic",
    "electronegativity": 2.33,
    "electron_configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Bismuth",
    "symbol": "Bi",
    "atomic_number": 83,
    "atomic_mass": 208.98,
    "category": "Post-Transition",
    "group": 15,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 2.02,
    "electron_configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Polonium",
    "symbol": "Po",
    "atomic_number": 84,
    "atomic_mass": 209.0,
    "category": "Post-Transition",
    "group": 16,
    "valency": 2,
    "common_charge": "+2/+4",
    "bonding_type": "Metallic",
    "electronegativity": 2.00,
    "electron_configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Astatine",
    "symbol": "At",
    "atomic_number": 85,
    "atomic_mass": 210.0,
    "category": "Metalloids",
    "group": 17,
    "valency": 1,
    "common_charge": "-1",
    "bonding_type": "Covalent",
    "electronegativity": 2.20,
    "electron_configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    "state": "Solid",
    "hex_code": "#14b8a6"
  },
  {
    "element": "Radon",
    "symbol": "Rn",
    "atomic_number": 86,
    "atomic_mass": 222.0,
    "category": "Noble Gases",
    "group": 18,
    "valency": 0,
    "common_charge": "0",
    "bonding_type": "Atomic",
    "electronegativity": 2.20,
    "electron_configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    "state": "Gas",
    "hex_code": "#ec4899"
  },
  {
    "element": "Francium",
    "symbol": "Fr",
    "atomic_number": 87,
    "atomic_mass": 223.0,
    "category": "Alkali Metals",
    "group": 1,
    "valency": 1,
    "common_charge": "+1",
    "bonding_type": "Metallic",
    "electronegativity": 0.79,
    "electron_configuration": "[Rn] 7s¹",
    "state": "Solid",
    "hex_code": "#ef4444"
  },
  {
    "element": "Radium",
    "symbol": "Ra",
    "atomic_number": 88,
    "atomic_mass": 226.0,
    "category": "Alkaline Earth",
    "group": 2,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 0.90,
    "electron_configuration": "[Rn] 7s²",
    "state": "Solid",
    "hex_code": "#f97316"
  },
  {
    "element": "Actinium",
    "symbol": "Ac",
    "atomic_number": 89,
    "atomic_mass": 227.0,
    "category": "Actinides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.10,
    "electron_configuration": "[Rn] 6d¹ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Thorium",
    "symbol": "Th",
    "atomic_number": 90,
    "atomic_mass": 232.04,
    "category": "Actinides",
    "group": 3,
    "valency": 4,
    "common_charge": "+4",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Rn] 6d² 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Protactinium",
    "symbol": "Pa",
    "atomic_number": 91,
    "atomic_mass": 231.04,
    "category": "Actinides",
    "group": 3,
    "valency": 5,
    "common_charge": "+5",
    "bonding_type": "Metallic",
    "electronegativity": 1.50,
    "electron_configuration": "[Rn] 5f² 6d¹ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Uranium",
    "symbol": "U",
    "atomic_number": 92,
    "atomic_mass": 238.03,
    "category": "Actinides",
    "group": 3,
    "valency": 6,
    "common_charge": "+6",
    "bonding_type": "Metallic",
    "electronegativity": 1.38,
    "electron_configuration": "[Rn] 5f³ 6d¹ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Neptunium",
    "symbol": "Np",
    "atomic_number": 93,
    "atomic_mass": 237.0,
    "category": "Actinides",
    "group": 3,
    "valency": 5,
    "common_charge": "+5",
    "bonding_type": "Metallic",
    "electronegativity": 1.36,
    "electron_configuration": "[Rn] 5f⁴ 6d¹ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Plutonium",
    "symbol": "Pu",
    "atomic_number": 94,
    "atomic_mass": 244.0,
    "category": "Actinides",
    "group": 3,
    "valency": 4,
    "common_charge": "+4",
    "bonding_type": "Metallic",
    "electronegativity": 1.28,
    "electron_configuration": "[Rn] 5f⁶ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Americium",
    "symbol": "Am",
    "atomic_number": 95,
    "atomic_mass": 243.0,
    "category": "Actinides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Rn] 5f⁷ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Curium",
    "symbol": "Cm",
    "atomic_number": 96,
    "atomic_mass": 247.0,
    "category": "Actinides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Rn] 5f⁷ 6d¹ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Berkelium",
    "symbol": "Bk",
    "atomic_number": 97,
    "atomic_mass": 247.0,
    "category": "Actinides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Rn] 5f⁹ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Californium",
    "symbol": "Cf",
    "atomic_number": 98,
    "atomic_mass": 251.0,
    "category": "Actinides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Rn] 5f¹⁰ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Einsteinium",
    "symbol": "Es",
    "atomic_number": 99,
    "atomic_mass": 252.0,
    "category": "Actinides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Rn] 5f¹¹ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Fermium",
    "symbol": "Fm",
    "atomic_number": 100,
    "atomic_mass": 257.0,
    "category": "Actinides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Rn] 5f¹² 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Mendelevium",
    "symbol": "Md",
    "atomic_number": 101,
    "atomic_mass": 258.0,
    "category": "Actinides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Rn] 5f¹³ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Nobelium",
    "symbol": "No",
    "atomic_number": 102,
    "atomic_mass": 259.0,
    "category": "Actinides",
    "group": 3,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Rn] 5f¹⁴ 7s²",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Lawrencium",
    "symbol": "Lr",
    "atomic_number": 103,
    "atomic_mass": 266.0,
    "category": "Actinides",
    "group": 3,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 1.30,
    "electron_configuration": "[Rn] 5f¹⁴ 7s² 7p¹",
    "state": "Solid",
    "hex_code": "#fb7185"
  },
  {
    "element": "Rutherfordium",
    "symbol": "Rf",
    "atomic_number": 104,
    "atomic_mass": 267.0,
    "category": "Transition Metals",
    "group": 4,
    "valency": 4,
    "common_charge": "+4",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d² 7s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Dubnium",
    "symbol": "Db",
    "atomic_number": 105,
    "atomic_mass": 268.0,
    "category": "Transition Metals",
    "group": 5,
    "valency": 5,
    "common_charge": "+5",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d³ 7s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Seaborgium",
    "symbol": "Sg",
    "atomic_number": 106,
    "atomic_mass": 269.0,
    "category": "Transition Metals",
    "group": 6,
    "valency": 6,
    "common_charge": "+6",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d⁴ 7s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Bohrium",
    "symbol": "Bh",
    "atomic_number": 107,
    "atomic_mass": 270.0,
    "category": "Transition Metals",
    "group": 7,
    "valency": 7,
    "common_charge": "+7",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d⁵ 7s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Hassium",
    "symbol": "Hs",
    "atomic_number": 108,
    "atomic_mass": 269.0,
    "category": "Transition Metals",
    "group": 8,
    "valency": 8,
    "common_charge": "+8",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d⁶ 7s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Meitnerium",
    "symbol": "Mt",
    "atomic_number": 109,
    "atomic_mass": 278.0,
    "category": "Transition Metals",
    "group": 9,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d⁷ 7s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Darmstadtium",
    "symbol": "Ds",
    "atomic_number": 110,
    "atomic_mass": 281.0,
    "category": "Transition Metals",
    "group": 10,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d⁸ 7s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Roentgenium",
    "symbol": "Rg",
    "atomic_number": 111,
    "atomic_mass": 282.0,
    "category": "Transition Metals",
    "group": 11,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d⁹ 7s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Copernium",
    "symbol": "Cn",
    "atomic_number": 112,
    "atomic_mass": 285.0,
    "category": "Transition Metals",
    "group": 12,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    "state": "Solid",
    "hex_code": "#eab308"
  },
  {
    "element": "Nihonium",
    "symbol": "Nh",
    "atomic_number": 113,
    "atomic_mass": 286.0,
    "category": "Post-Transition",
    "group": 13,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Flerovium",
    "symbol": "Fl",
    "atomic_number": 114,
    "atomic_mass": 289.0,
    "category": "Post-Transition",
    "group": 14,
    "valency": 4,
    "common_charge": "+4",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Moscovium",
    "symbol": "Mc",
    "atomic_number": 115,
    "atomic_mass": 290.0,
    "category": "Post-Transition",
    "group": 15,
    "valency": 3,
    "common_charge": "+3",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Livermorium",
    "symbol": "Lv",
    "atomic_number": 116,
    "atomic_mass": 293.0,
    "category": "Post-Transition",
    "group": 16,
    "valency": 2,
    "common_charge": "+2",
    "bonding_type": "Metallic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    "state": "Solid",
    "hex_code": "#22c55e"
  },
  {
    "element": "Tennessine",
    "symbol": "Ts",
    "atomic_number": 117,
    "atomic_mass": 294.0,
    "category": "Halogens",
    "group": 17,
    "valency": 1,
    "common_charge": "-1",
    "bonding_type": "Covalent",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    "state": "Solid",
    "hex_code": "#a855f7"
  },
  {
    "element": "Oganesson",
    "symbol": "Og",
    "atomic_number": 118,
    "atomic_mass": 294.0,
    "category": "Noble Gases",
    "group": 18,
    "valency": 0,
    "common_charge": "0",
    "bonding_type": "Atomic",
    "electronegativity": 0.0,
    "electron_configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    "state": "Solid",
    "hex_code": "#ec4899"
  }
]

export default AtomData